### ISSUE TITLE
Once logged auto-redirect to the main character' profession page

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#100]
Hello.

Once we are logged to the gateway website (with login automatically) we are directly redirected to our main character's profession page. On settings we are able to choose which one are the main character.

Regards'

**Comment by Phr33d0m** [comment]
Incorrect. The script doesnt't care one bit about who's your main character. It will first try to go to the latest character it was working on and then will restart from the beginning of the list (this was as of 3.0).

**Comment by GeneralSheppard** [comment]
Interesting explication. 
Thank you.
