### ISSUE TITLE
Be disconnected when we click on "Sign out"; no auto-sign in right after.

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#101]
Hello.

With "Attempt to login automatically" enabled to get logged automatically when we open our chrome profile shortcut; it would be interesting to be disconnected when we click on "Sign out".

Right now when we click to "Sign out" the script attempt again to login automatically. 
It does his job right but if we need to sign out it's to be disconnected.
Anyway we can also close the chrome page.

Thanks

**Comment by Phr33d0m** [comment]
Pause the script, click sign out. Sorry but there's nothing to do here.
