### ISSUE TITLE
#Inventory Auto-Vendor button  rename as Sell button ?

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#106]
Hello.

Players do recognize that 'auto-selling' button do not exist on native gateway feature.
- Would it be possible to change the button text 'Auto Vendor' to 'Sell' to fit with 'Sort' button ?
- The pop-up saying that we sold an item for x currency do not close automatically. It would be interesting that it becomes automatic to maintain the "auto-vendor" feature who is automatic after few seconds.

If not where is located exactly this 'text button' to custom our local script ? 

Thank you.

**Comment by dlebedynskyi** [comment]
Trick is that auto vendor does not just sell. It is configurable to know what to see- junk, rune-stones and so on. 
Maybe auto sell be better  instead of just sell?

**Comment by GeneralSheppard** [comment]
I am agree to this one.
