### ISSUE TITLE
About the new pop-message (Setting wipe confirmation)

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#111]
Hello.

Fresh script installation with my friend where none previous script was installed on his Gateway account and on his own computer he got the main message about Setting wipe confirmation box. Here are our feedback and few requests:
- IF a player is doing his first script installation it would be confusing to get that Setting wipe confirmation box knowing that it's the first time he is using it.
- Enhanced welcome message box:
  ---- Script name   v3.xx  by  Authors
  ---- Short script description, few lines who describe what this script do exactly
  ---- Main new feature, need to click on changelog link to view full list
  ---- NEVERWINTER Username/Password
  ---- Attempt to login automatically
  ---- Choose Language

---- VIEW changelog link : redirect here or greasfork
---- Development page link : HERE
---- Main page : greasfork
---- Report bug: redirect to Github issue page

Like:  changelog  github  greasfork  report a bug

The Wipe confirmation is display under !important! if the script detects previous old settings or previous installation.

CONTINUE AND PLAY buton

With this enhanced welcome box it's possible to cleanup this Script settings (remove language, login info, check autologin) and avoid us to click on the setting icon.

Here we are we have almost everything needed to start directly working with our profession script.

Best regards

**Comment by noonereally** [comment]
Why would I want for the user to avoid clicking the settings ? 
1. The user must set the active characters.
2. There was a considerable amount of work done to add some info to the settings tabs, for some it may not be useful, but 'preventing' people to even look at that is not encouraging... 
3. If i don't want to auto login and save the password ?

How I see it, the script was not meant for 'just install'. 
It has two functions, make tedious tasks easy like opening reward boxes, selling junk, consolidation and so on.
And the other was to give the user the control he needs to get the most out of the professions and gateway. From the custom profiles, various settings for optional assets, mass/not mass refining and to the info tabs, and per char settings.

Perhaps it's not the most friendly for new users that just want to install and have it all ready for them, but at least my changes were not meant for it. Not that there is an attempt to make it unfriendly, but there is more emphasis to make more 'advanced' features, to allow users to get more out of the gateway.

**Comment by GeneralSheppard** [comment]
I mean for the first step installation we have to click on the setting icon only to put username/password and check autologin then click on play button. 

It would be interesting to have this at the beginning during the first pop up windows introducing the script purpose and the warning about the wipe setting.

Then of course clicking on the settings are important I just wanted to share how cool it will be to have this kind of windows.
1. Does the script work even if we do not put username and password ? I didn't try it.

I never said to avoid users to click settings and avoid them to have a look into the advanced the script settings just to enhance the first windows that come when users install it. Then they are free to put their login infos or not.

Something like this: sorry for the pics:

http://prntscr.com/7739xp

**Comment by dlebedynskyi** [comment]
@noonereally  good job on this update. 
Testing new char settings now. In general I was surprised by message at first  and I m impressed by  amount of work did in few days I was gone. Good job!

**Comment by Phr33d0m** [comment]
I've said it countless times before: if the user is not smart enough to use the bot then it's better for that person not to do it.

Window with "hi I'm the bot, here's my changelog" is just completely useless. When your Google Chrome updates do you see any "here's our changelog" kind of link/window? Do you even google the changelog and read through it?

For the ones that care, will do their homework and search for it.
