### ISSUE TITLE
ZeX don't work

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#119]
hello, with the last version 3.5 the zex don't work. i d'ont know why because have set Zex in account configuration and for all my character.
i have perhaps miss something but i don't know what ?
my configuration : 
Consolidate AD via ZEX
Character Name of Banker [deleted]
Min AD for Transfer 24000
Min Character balance 0
AD per Zen Rate (in zen) 50

and for each character : 
Min AD for Transfer 24000
Min Character balance 0

and the debug log : 
Next finished task at 24/5/2015 14:53:32
VM7951:2083 [deleted]'s Astral Diamonds: 31854
VM7951:4552 Attempting to vendor selected items...

for this character it's normal , the 24K is not  reach: 
[deleted]'s Astral Diamonds: 23232
VM7951:3037 Character does not have minimum AD balance to do funds transfer. Skipping Zex Posting..
VM7951:4552 Attempting to vendor selected items...

best regard

**Comment by noonereally** [comment]
You do not need to set it for each character unless you want a character with a different setting than all the rest and then you have to set the "override settings" checkbox too.

Your issue:
~~Try not setting "Min Character balance" to 0. Set it to anything else, like 1.~~
Do you have Override Account settings on for the first char the failed ? And if so is the consolidation on in her tab ?
You shouldn't have 'Override Account settings' on.

On another thought, Do you have the bank character set correctly ?

Also I wouldn't recommend doing so many transfers, I would recommend larger 'Min AD for Transfer'. But it will work with 24k.

**Comment by djconnexion** [comment]
i have put the override for all my character and has you can see i have  config correctly the ZeX for account.

with the 3.1 version this configuration work perfectly

**Comment by noonereally** [comment]
Please try the version now.
There was an error in the override, 3.1 didn't have override at all, so it worked. should work now.

May I ask, Is there a specific setting that because of it you put _all_ the chars with override enabled ?
I was expecting for people to have most characters **not** in override.

**Comment by djconnexion** [comment]
yes  i pull all my character with override.
they work perflectly to make the  zex, but they don't cancel zex and  don't withdraw.

**Comment by djconnexion** [comment]
this the debug log : 
Elwira's Astral Diamonds: 345043
VM162:3041 Bank char not set or bank char, skipping posting.
 as you can see in my first post  i have set a bank char.
do you think it 's because i have check th zex in the char tab ?

if i understand  when i put override on my all char don't need to check all zex in char tab ?

**Comment by noonereally** [comment]
You have disabled the consolidation in the account. 
I've changed it now so if the bank in override and have it enabled, the bank will withdraw. 
Try it now, sorry for the trouble.

If you put override on all chars (not sure why) you must check consolidation on all the chars you want to post AD and on the bank char.

**Comment by djconnexion** [comment]
ok i  uncheck and recheck now and i test  it : 
Saved char setting: char.consolidationSettings.consolidate For: [deleted]
2(program):4001 Saved account setting: account.consolidationSettings.consolidate For: [deleted]

**Comment by noonereally** [comment]
Do not post your account name.
Characters also not advised!  I've removed what I saw.  Just put in Char1, Char2 instead of names.

I've updated the script earlier, so it should work with your settings:
Override on all, ZAX Consolidation enabled on chars and bank, ZAX Consolidation Disabled on account.

**Comment by djconnexion** [comment]
with the new version theydon't work  : 
Zen Max Listings Reached (5). Skipping Zex Posting..
VM187:2823 Canceling ZEX orders
.....
Loaded zen exchange data for banker@account
....
Canceling ZEX orders
....
Banker's Astral Diamonds: 174256
VM187:3042 Bank char not set or bank char, skipping posting.

**Comment by noonereally** [comment]
Updated.

**Comment by djconnexion** [comment]
ok  i have unchecked override  and zex on my character banker and  they seem working perfectly now .
this the log  : 
Canceling ZEX orders
VM154:2834 Canceling Zex offer for 1600 ZEN at the rate of 50 . Total value in AD: 80000
VM154:2834 Canceling Zex offer for 1720 ZEN at the rate of 50 . Total value in AD: 86000
VM154:2834 Canceling Zex offer for 576 ZEN at the rate of 50 . Total value in AD: 28800
....
Loaded zen exchange data for banker@account
VM154:2849 Attempting to withdraw exchange balancees... ClaimTC: 194800

i test it more  to see if it's really working .
thx a lot  for the quick update

**Comment by djconnexion** [comment]
this is ok work perfectly now

**Comment by Phr33d0m** [comment]
Cool. Good work @noonereally.
