### ISSUE TITLE
Unnecessary loop?

### ISSUE THREAD

**Issue by zalex11** [Phr33d0m/NW-Profession-Bot#123]
``` js
charNamesList.every( function (charName, idx) {
            if (!charSettingsList[charName].general.active) {
                not_active++;
                return true;
            }
            if (chartimers[idx] != null) {
                console.log("Date found for " + charName);
                if (!chardate || chartimers[idx] < chardate) {
                    chardate = chartimers[idx];
                    curCharNum = idx;
                    chardelay = chardate.getTime() - nowdate - unsafeWindow.client.getServerOffsetSeconds() * 1000;
                    if (chardelay < delay.SHORT) {
                        chardelay = delay.SHORT;
                    }
                }
                return true;
            } 

            curCharNum = idx;
            chardelay = delay.SHORT;
            chardate = null;
            console.log("No date found for " + charName + ", switching now.");
            return false; // = break; 
        });

charNamesList.forEach( function (charName, idx) {
            if (chardiamonds[idx] != null) {
                curdiamonds += Math.floor(chardiamonds[idx] / 50) * 50;
            }

            if (chargold[idx] != null) {
                curgold += chargold[idx];
            }
        });
```

can the diamond and gold total's update be placed inside the the first loop?

**Comment by noonereally** [comment]
Every and forEach are not the same. Every is broken on false. foreach will always complete.
You will need to save the first null time and add a check for it to make it in one loop.
Computationally it will be the same as O(n) + O(n) vs O(2*n), both are O(n) where n is the char number and limited to 52, hence can be written as O(1).

**Comment by zalex11** [comment]
As far as I know you can have 54 char slots (First time buyer [1] + dragon born pack [1] + buying 25 slot pairs + 2 free).
With BigO the actual runtime would be different between O(2n) and O(n).
If merged what would make something like below incorrect? This is being called every switchChar() could it be reduced to just add the delta of ad/gold from the last visit of the current character instead of recalculating it every time?

``` js
charNamesList.every( function (charName, idx) {
            if (chardiamonds[idx] != null) {
                curdiamonds += Math.floor(chardiamonds[idx] / 50) * 50;
            }

            if (chargold[idx] != null) {
                curgold += chargold[idx];
            }
            if (!charSettingsList[charName].general.active) {
                not_active++;
                return true;
            }
            if (chartimers[idx] != null) {

                return true;
            } 
```

**Comment by noonereally** [comment]
It's 52 total, the 2 free are part of the total 50 you can buy. (you can buy 48) 

While your example will be considered eventually O(n), we begin with worst case execution of something like 9n, One loop that will run n times and 9 operations in it,  O(9n) -> O(n)
(even more considering ```charSettingsList[charName]``` is not O(1), but more like O(n) so you get O(n^2))

If we split that example to lets say 4 loops, a loop per block, we will get 
O(4n) + O(2n) + O(2n) + O(n) = O(9n) = O(n).

But of course there is the loop itself, the one you actually trying to remove and therefore optimize, 
a simple traversal like forEach or for (i = 0<; ; i++) can be considered O(1), 
for this as I wrote earlier in non scripted languages a pass over a sequential array will be faster or the same speed as adding a branch into an existing loop even though on paper the ```for``` has more operations than an ```if```.
In a script it's depends on the implementation, but with the overhead it's safe to assume it's worse.

At the end doing two loops or one with the same code is an issue of code readability and separation and not computational complexity. 

In real life you are trying to optimize the wrong thing, what is the complexity of this block ?
```
$('div.notification div.messages li').waitUntilExists(function() {
        if ($("div.notification div.messages li").length > 2)
            $("div.notification div.messages li").eq(0).remove();
    });
```
Or for example the nice timer on top that shows you how much time to next script, it's updated every second, how the browser knows what elements to update ? And what is the complexity of a DOM search ?
You are trying to optimize a loop called once per char swap, in normal condition it's once per few minutes or even few hours.

To the gold question, looping over 52 items is negligible in a system that uses the DOM and it's rules.
Calculating a gold delta will make the code more complex to upkeep and more prone to errors, 
Try to implement it.. 
More so, my advice, test stuff with a profiler before you put to much effort in it.

**Comment by zalex11** [comment]
I know nothing about web/scripting languages.

**Comment by Phr33d0m** [comment]
@zalex11 nothing about programming it seems.

@noonereally I'm quite impressed with the huge amount of letters you put into that response ;-)

**Comment by zalex11** [comment]
... the is no reason to write 2 loops when 1 would suffice. BigO is nice for analyzing algorithms but doesn't exactly apply when doing real world because you don't have infinite sets. You wouldnt want to loop over a billion items twice when once would do. I implemented what i wrote and it works fine. no need to be as asshole.

**Comment by noonereally** [comment]
I've put the time and explained in detail why it doesn't matter.  And you call me an ass hole ?
BigO is not used on infinite sets but in real life with estimated input, though as i said in real life there are profiles and automated tests to help.

If the gold counter made persistent or taken from the stats structure,  
how much gold the counter will show in this case:
char 1 - time, char 2 - time, char 3 - null, char 4 - null, char 5 - time
with 
[100, 100, 100, 5000, 5000] gold respectively.
In the original code 10300, in your code 200.

**Comment by zalex11** [comment]
not you, phr33dom.
my code works for me because my characters should never have null times.

**Comment by noonereally** [comment]
Then you should use forEach as  every uses exit check every iteration that apparently you do not need. And remove:
```
            curCharNum = idx;
            chardelay = delay.SHORT;
            chardate = null;
            console.log("No date found for " + charName + ", switching now.");
            return false; // = break; 
```
Otherwise what is the purpose of that block.
And the check:
```
if (chartimers[idx] != null)
```
As it is useless.

**Comment by Phr33d0m** [comment]
@zalex11 well sorry about that then.
