### ISSUE TITLE
Alchemy will get stuck if there is not enough gold.

### ISSUE THREAD

**Issue by noonereally** [Phr33d0m/NW-Profession-Bot#124]
There are no gathering tasks so even the refine task can fail if there is not enough gold to buy solvent and enter a loop.

https://greasyfork.org/en/forum/discussion/4453/x

**Comment by dlebedynskyi** [comment]
This is curious cause from what i see now we have "Artificing_Tier1_Gather_Basic"  now in alchemy as fall back. Was it fixed?

**Comment by noonereally** [comment]
hmm weird, I just checked, don't see the gathering

**Comment by dlebedynskyi** [comment]
@noonereally  nervermind. my bad being blind.

**Comment by noonereally** [comment]
Thanks, I hate touching profiles.
