### ISSUE TITLE
Delay after collecting rewards

### ISSUE THREAD

**Issue by HenryLoenwind** [Phr33d0m/NW-Profession-Bot#132]
Looking at https://github.com/Phr33d0m/NW-Profession-Bot/blob/master/main.js#L2008

So it collects all rewards and then takes a "default" (long) nap. I wonder if it wouldn't be smoother to take a short nap after each reward instead. This works fine in my (very limited) test:

```
    // Collect rewards for completed tasks and restart
    if (unsafeWindow.client.dataModel.model.ent.main.itemassignments.complete) {
        unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.forEach(function(entry) {
            if (entry.hascompletedetails) {
                unsafeWindow.client.professionTaskCollectRewards(entry.uassignmentid);
                dfdNextRun.resolve(delay.SHORT);
                return true;
            }
        });
    }
```

Am I overlooking something here?

**Comment by noonereally** [comment]
The main difference I see is that there is now less time between the last collected item and the slot allocation. It isn't a problem in your change as is, because if the model was not updated in time you will try to collect again, fail, and restart again.

But your post gave me an idea how to solve  
https://github.com/Phr33d0m/NW-Profession-Bot/issues/53

We can add
`var triedToCollect = [false, false....false]` 9 - slots 

Setting it to false on switchChar too, and then

```
    // Collect rewards for completed tasks and restart
    if (unsafeWindow.client.dataModel.model.ent.main.itemassignments.complete) {
    var restart = false; 
    unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.forEach(function(entry, idx) {
                if (entry.hascompletedetails && !triedToCollect[idx]) {
                    unsafeWindow.client.professionTaskCollectRewards(entry.uassignmentid);
                    triedToCollect[idx] = true;
                    restart = true;
                }
            });
            if (restart) {
                    dfdNextRun.resolve();
                    return true;
            }
        }
```

Needs testing, and probably can be done better but should work.
Should also work with the restart after each collection, but then the only issue is on slow model update. If the model was not updated in time after the last slot collected and we reached this code again, it will skip the slot because it's marked as 'was attempted to collect'.

**Comment by HenryLoenwind** [comment]
Maybe store a timestamp for the attempted collection for each slot and do not try to collect again for, say, 1 minute? What I don't know is, how good the script is in picking up that a slot goes ready/empty 'unexpectedly' (model updating late).

BTW: Yes, my code posted above was garbage. Moving a return into an anonymous function doesn't really work. Optimization fail... (I blame it on coding too much Java the last couple of months.)

This is what I'm running atm:

```
    // Collect rewards for completed tasks and restart
    if (unsafeWindow.client.dataModel.model.ent.main.itemassignments.complete) {
        var done = false;
        unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.forEach(function(entry) {
            if (!done && entry.hascompletedetails) {
                unsafeWindow.client.professionTaskCollectRewards(entry.uassignmentid);
                done = true;
            }
        });
        dfdNextRun.resolve(delay.SHORT);
        return true;
    }
```

I haven't seen any more bogus "cannot collect"s with this. I think the 1 second pause after each collection helps the model to update properly. Also it gets rid of the overly long pause between collecting and starting a new task. (It makes no sense to pretend to be human here but then collect all slots within the same second on the other hand.)

**Comment by HenryLoenwind** [comment]
PS: I was thinking about something like (pseudo code!):

```
    // Collect rewards for completed tasks and restart
    if (unsafeWindow.client.dataModel.model.ent.main.itemassignments.complete) {
        var done = false;
        unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.forEach(function(entry) {
            if (!done && entry.hascompletedetails && lastcollect{charname + ':' + slotnumber} < now() - 60) {
                unsafeWindow.client.professionTaskCollectRewards(entry.uassignmentid);
                lastcollect{charname + ':' + slotnumber} = now();
                done = true;
            }
        });
        if (done) {
            dfdNextRun.resolve(delay.SHORT);
            return true;
        }
    }
```

**Comment by noonereally** [comment]
I didn't even look closely at the code. Got the general idea...

About the code then, maybe changing it to .every 
`unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.every(...`
the false will break it and return true will keep it going.  
Something like:

```
  // Collect rewards for completed tasks and restart
    if (unsafeWindow.client.dataModel.model.ent.main.itemassignments.complete) {
        if (!unsafeWindow.client.dataModel.model.ent.main.itemassignments.assignments.forEach(function(entry, idx) {
            if (entry.hascompletedetails && lastcollect[idx] < now() - 1000) {
                unsafeWindow.client.professionTaskCollectRewards(entry.uassignmentid);
                if (!lastcollect[idx]) lastcollect[idx] = now();
                return false;
            }
            return true;
        }))  {
            dfdNextRun.resolve(delay.SHORT);
            return true;
        }
    }

```

Maybe a time-stamp will work (JavaScript timestamps are in milliseconds so it's 1000 for 1 sec),
but perhaps there is a betters solution, when the gateway lags it takes more than one second to respond, and if adding a delay it should probably also use the delay factor setting.

Also an option is to change the array to counters and increase each attempt, if we did more than 3 attempt we skip it. Each attempt has the `dfdNextRun.resolve(delay.SHORT);` So I think it's a more reliable way. Also the number of attempts can be added to settings, so people that experience lag or less reliable connection can set it to lets say 3 while others can keep it on 1-2.  

You can't just set `lastcollect[idx] = now();` inside, it will cause the same infinite loop on error if all the repetitions under 1 second. 

I don't think there is need to save for each char, as this should be set to 0 each char switch.

Why the {} brackets on the object ? You can access properties with curly brackets ?

**Comment by noonereally** [comment]
Committed the counter version. Testing appreciated.

**Comment by HenryLoenwind** [comment]
ok, I researched the Javascript syntax for what I want to do. I'll try this out at home tonight:

https://github.com/HenryLoenwind/NW-Profession-Bot/commit/b5a3facbef88ca6dc84bb41795bd10e216a4226e

**Comment by noonereally** [comment]
I'm not sure if a time check is necessary,  each attempt has underlying `delay.SHORT * delayFactor` 
so after 3 attempts i'm assured I've waited `3 * delay.SHORT * delayFactor`
And it makes sure it wont hammer the command repeatedly.

**Comment by Phr33d0m** [comment]
Open a new issue if this is still a thing.
