### ISSUE TITLE
Grouping and names  for inventory items

### ISSUE THREAD

**Issue by dlebedynskyi** [Phr33d0m/NW-Profession-Bot#136]
Just an idea that might be useful a lot. 
Can we actually group items by their names 
like 
1 Crafted_Leatherworking_T3_Leather_Shirt_3c
1 Crafted_Leatherworking_T3_Leather_Shirt_3c 

should be just simply  - total 2 shirts ? with human name if possible.  

@WloBeb what do you think ? 
separation by bag is ok but  it could be way more useful for me to know counts of some items total  in all bags and how much free slots i have.

**Comment by Phr33d0m** [comment]
Printing human readable names is nice, although... isn't everything else you said already implemented in 'Inventory Listing'?

**Comment by dlebedynskyi** [comment]
@Phr33d0m  no. It is grouping by bag now as far as I remember. I would like to see grouping by name across all bags.

**Comment by noonereally** [comment]
The inventory listing was mainly made as a quick tool to find the gateway model name of the items, It's by bags so for example if I see the item I need in fifth slots in third bag, I can look at the list and find it. Some of the names are generic like resonance stone is something like  artigear_food_r1.

To see a sum of specific items I think it will be better to use the tracker.

**Comment by dlebedynskyi** [comment]
@noonereally  was open before tracker appeared. closing now.
