### ISSUE TITLE
Notification for missing resources

### ISSUE THREAD

**Issue by HenryLoenwind** [Phr33d0m/NW-Profession-Bot#138]
I've been using this for the last days: https://github.com/HenryLoenwind/NW-Profession-Bot/commit/47621c1d6b3d6e6ada4874c1ad09499eaf1833c1

It works quite well, but it is not nice enough to be PRed, I'd say.

**Comment by dlebedynskyi** [comment]
we might want to merge this. @HenryLoenwind  can you make a pull request? it could be handing to have this.

**Comment by HenryLoenwind** [comment]
sure

#146

**Comment by Phr33d0m** [comment]
PR merged.
