### ISSUE TITLE
4.1 Hanging

### ISSUE THREAD

**Issue by paladinpizza** [Phr33d0m/NW-Profession-Bot#139]
As reported in this thread:

https://greasyfork.org/en/forum/discussion/4694/x

The script randomly locks up when collecting rewards, and hangs until I close the browser and restart, and/or log out and log back into the gateway. It happens randomly on any character - max leadership with AD or resource/ad profiles, and also on a toon that's leveling up (and I do have assets and resources available). Letting the script sit for upwards of 1-2 hours does not alter behavior. I have uninstalled the script, closed out the browser, restarted the machine, then reinstalled - same events are still occurring. I'm using 4.1 and Chrome Version 43.0.2357.124 m, with Tampermonkey 3.11 . 

Edit and add'l info: This started post patch this week, prior to everything worked without a hitch. Is it possible something has changed on the gateway that is causing this?

**Comment by noonereally** [comment]
I've noticed something strange after the patch, 
The error appears to be that  this is undefined 

```
        // start task if requirements are met
        if (!thisTask.failedrequirementsreasons.length) {
            return thisTask;
        }
```

I've added a simple check but it didn't happen since.

If you (or anyone) can add the relevant log, because the error described in that thread is not the same I saw.

**Comment by Phr33d0m** [comment]
I haven't seen any issues as described in greasyfork or as per @paladinpizza's use case (as mine is the same).

Could you enable debugging in the script then open your chrome console (usually F12) and copy/paste us the last 50-100 lines when the script hangs? That'd be way more helpful.

**Comment by noonereally** [comment]
![capture](https://cloud.githubusercontent.com/assets/10575011/8292430/497aac8e-1938-11e5-916c-b85f84c7d8e0.PNG)
It's a gateway issue, the `failedrequirementsreasons` is not defined on some of the tasks.

I've made a small fix, needs testing.

**Comment by paladinpizza** [comment]
I hope this is what you wanted?  At the time of me posting this script, it looks like it collected 2 tasks.  Guard Young Noble (1 occurrence) was complete and ready to be collected, Destroy Enemy Camp (1 occurrence) was complete and ready to be collected, 3 instances of Battle Elemental Cultists (2 ready to collect, 1 still in process), Provide Security For Pilgrims (2 occurrences) was complete and ready to be collected, and there were 2 empty slots. Logging out, script kicked off and then logged back in  and began to operate normally.  Pausing/Unpausing prior to logout had no effect.

Loading gateway script for toon@toon
VM16962:3590 Loaded datamodel for toon@toon
VM16962:3584 Loading gateway script for toon@toon
VM16962:3590 Loaded datamodel for toon@toon
VM16962:3606 Loaded zen exchange toon@toon
VM16962:3644 Loaded profession merchant for toon@toon
VM16962:4825 Attempting to vendor selected items...
VM16962:2096 Looking for empty slots.
VM16962:2125 Prioritizing task lists.
VM16962:2134 Attempting to fill the slot.
VM16962:2144 Selecting profile: Resource/AD
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 0
VM16962:2356 Searching for task: Leadership_Tier4_25r_Huntexperiment
VM16962:2485 Could not find task for: Leadership_Tier4_25r_Huntexperiment
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 1
VM16962:2356 Searching for task: Leadership_Tier4_24r_Killdragon
VM16962:2485 Could not find task for: Leadership_Tier4_24r_Killdragon
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 2
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master2
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master2
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 3
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master1
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master1
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 4
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master3
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master3
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 5
VM16962:2356 Searching for task: Leadership_Tier4_23r_Securepilgrimage
VM16962:2485 Could not find task for: Leadership_Tier4_23r_Securepilgrimage
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 6
VM16962:2356 Searching for task: Leadership_Tier4_25_Battleelementalcultists
VM16962:2485 Could not find task for: Leadership_Tier4_25_Battleelementalcultists
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 7
VM16962:2356 Searching for task: Leadership_Tier4_24_Wizardsseneschal
VM16962:2485 Could not find task for: Leadership_Tier4_24_Wizardsseneschal
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 8
VM16962:2356 Searching for task: Leadership_Tier4_23_Guardnoble
VM16962:2371 Task Found
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T3_Epic
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T3_Rare
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T3_Uncommon
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T3_Common
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T2_Common
VM16962:2431 Checking bags for Crafting_Asset_Craftsman_Leadership_T1_Common_1
VM16962:2768 Clicked item
VM16962:2384 Items Populated
VM16962:2389 Clicking Start Task Button
VM16962:2096 Looking for empty slots.
VM16962:2125 Prioritizing task lists.
VM16962:2134 Attempting to fill the slot.
VM16962:2144 Selecting profile: Resource/AD
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 0
VM16962:2356 Searching for task: Leadership_Tier4_25r_Huntexperiment
VM16962:2485 Could not find task for: Leadership_Tier4_25r_Huntexperiment
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 1
VM16962:2356 Searching for task: Leadership_Tier4_24r_Killdragon
VM16962:2485 Could not find task for: Leadership_Tier4_24r_Killdragon
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 2
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master2
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master2
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 3
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master1
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master1
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 4
VM16962:2356 Searching for task: Leadership_Tier3_20r_Master3
VM16962:2485 Could not find task for: Leadership_Tier3_20r_Master3
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 5
VM16962:2356 Searching for task: Leadership_Tier4_23r_Securepilgrimage
VM16962:2485 Could not find task for: Leadership_Tier4_23r_Securepilgrimage
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 6
VM16962:2356 Searching for task: Leadership_Tier4_25_Battleelementalcultists
VM16962:2485 Could not find task for: Leadership_Tier4_25_Battleelementalcultists
VM16962:2419 Finding next task
VM16962:2352 Leadership is level 25
VM16962:2353 createNextTask 21 7
VM16962:2356 Searching for task: Leadership_Tier4_24_Wizardsseneschal
VM16962:2490 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by paladinpizza** [comment]
Here is the dump of settings:

Script Settings (script version 4.1)
{
    "general": {
        "saveCharNextTime": false,
        "scriptPaused": false,
        "language": "en",
        "scriptDebugMode": true,
        "scriptAutoReload": false,
        "autoLogin": true,
        "autoLoginAccount": "here@there.com",
        "autoLoginPassword": "password",
        "autoReload": true,
        "scriptDelayFactor": 1,
        "maxCollectTaskAttempts": "3"
    }
}
Account Settings
Bank set and found at index:0
{
    "vendorSettings": {
        "vendorJunk": true,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": true,
        "vendorPots1": true,
        "vendorPots2": true,
        "vendorPots3": true,
        "vendorPots4": true,
        "vendorPots5": false,
        "vendorEnchR1": true,
        "vendorEnchR2": true,
        "vendorEnchR3": true
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "smartLeadershipAssets": true,
        "skipPatrolTask": "AD&Lvl20"
    },
    "generalSettings": {
        "refineAD": true,
        "openRewards": true,
        "keepOneUnopened": false,
        "runSCA": "free",
        "SCADailyReset": 1434967475262
    },
    "consolidationSettings": {
        "bankCharName": "Char 0",
        "transferRate": 100,
        "consolidate": true,
        "minCharBalance": "1",
        "minToTransfer": "7148"
    }
}
Char Settings
Char 0
{
    "charName": "Char 0",
    "general": {
        "active": true,
        "overrideGlobalSettings": false,
        "manualTaskSlots": false
    },
    "vendorSettings": {
        "vendorJunk": false,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": false,
        "vendorPots1": false,
        "vendorPots2": false,
        "vendorPots3": false,
        "vendorPots4": false,
        "vendorPots5": false,
        "vendorEnchR1": false,
        "vendorEnchR2": false,
        "vendorEnchR3": false
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "skipPatrolTask": "AD&Lvl20",
        "smartLeadershipAssets": true
    },
    "generalSettings": {
        "refineAD": true,
        "keepOneUnopened": false,
        "openRewards": false,
        "runSCA": "free"
    },
    "consolidationSettings": {
        "consolidate": false,
        "minCharBalance": 10000,
        "minToTransfer": 50000
    },
    "taskListSettings": {
        "Leadership": {
            "taskSlots": 9,
            "taskProfile": "Resource/AD",
            "taskPriority": 2
        },
        "Jewelcrafting": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Alchemy": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Weaponsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Artificing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Mailsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Platesmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Leatherworking": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Tailoring": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "BlackIce": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "WinterEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "SiegeEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        }
    },
    "taskListSettingsManual": [
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        }
    ]
}
Char 1
{
    "charName": "Char 1",
    "general": {
        "active": true,
        "overrideGlobalSettings": false,
        "manualTaskSlots": false
    },
    "vendorSettings": {
        "vendorJunk": false,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": false,
        "vendorPots1": false,
        "vendorPots2": false,
        "vendorPots3": false,
        "vendorPots4": false,
        "vendorPots5": false,
        "vendorEnchR1": false,
        "vendorEnchR2": false,
        "vendorEnchR3": false
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "skipPatrolTask": "AD&Lvl20",
        "smartLeadershipAssets": true
    },
    "generalSettings": {
        "refineAD": true,
        "keepOneUnopened": false,
        "openRewards": false,
        "runSCA": "free"
    },
    "consolidationSettings": {
        "consolidate": false,
        "minCharBalance": 10000,
        "minToTransfer": 50000
    },
    "taskListSettings": {
        "Leadership": {
            "taskSlots": 9,
            "taskProfile": "Resource/AD",
            "taskPriority": 2
        },
        "Jewelcrafting": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Alchemy": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Weaponsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Artificing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Mailsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Platesmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Leatherworking": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Tailoring": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "BlackIce": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "WinterEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "SiegeEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        }
    },
    "taskListSettingsManual": [
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        }
    ]
}
Char 2
{
    "charName": "Char 2",
    "general": {
        "active": true,
        "overrideGlobalSettings": false,
        "manualTaskSlots": false
    },
    "vendorSettings": {
        "vendorJunk": false,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": false,
        "vendorPots1": false,
        "vendorPots2": false,
        "vendorPots3": false,
        "vendorPots4": false,
        "vendorPots5": false,
        "vendorEnchR1": false,
        "vendorEnchR2": false,
        "vendorEnchR3": false
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "skipPatrolTask": "AD&Lvl20",
        "smartLeadershipAssets": true
    },
    "generalSettings": {
        "refineAD": true,
        "keepOneUnopened": false,
        "openRewards": false,
        "runSCA": "free"
    },
    "consolidationSettings": {
        "consolidate": false,
        "minCharBalance": 10000,
        "minToTransfer": 50000
    },
    "taskListSettings": {
        "Leadership": {
            "taskSlots": 9,
            "taskProfile": "Resource/AD",
            "taskPriority": 2
        },
        "Jewelcrafting": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Alchemy": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Weaponsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Artificing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Mailsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Platesmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Leatherworking": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Tailoring": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "BlackIce": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "WinterEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "SiegeEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        }
    },
    "taskListSettingsManual": [
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        }
    ]
}
Char 3
{
    "charName": "Char 3",
    "general": {
        "active": true,
        "overrideGlobalSettings": false,
        "manualTaskSlots": false
    },
    "vendorSettings": {
        "vendorJunk": false,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": false,
        "vendorPots1": false,
        "vendorPots2": false,
        "vendorPots3": false,
        "vendorPots4": false,
        "vendorPots5": false,
        "vendorEnchR1": false,
        "vendorEnchR2": false,
        "vendorEnchR3": false
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "skipPatrolTask": "AD&Lvl20",
        "smartLeadershipAssets": true
    },
    "generalSettings": {
        "refineAD": true,
        "keepOneUnopened": false,
        "openRewards": false,
        "runSCA": "free"
    },
    "consolidationSettings": {
        "consolidate": false,
        "minCharBalance": 10000,
        "minToTransfer": 50000
    },
    "taskListSettings": {
        "Leadership": {
            "taskSlots": 9,
            "taskProfile": "Resource/AD",
            "taskPriority": 2
        },
        "Jewelcrafting": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Alchemy": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Weaponsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Artificing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Mailsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Platesmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Leatherworking": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Tailoring": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "BlackIce": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "WinterEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "SiegeEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        }
    },
    "taskListSettingsManual": [
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        }
    ]
}
Char 4
{
    "charName": "Char 4",
    "general": {
        "active": true,
        "overrideGlobalSettings": false,
        "manualTaskSlots": false
    },
    "vendorSettings": {
        "vendorJunk": false,
        "vendorKitsLimit": false,
        "vendorAltarsLimit": false,
        "vendorKitsAll": false,
        "vendorAltarsAll": false,
        "vendorProfResults": false,
        "vendorPots1": false,
        "vendorPots2": false,
        "vendorPots3": false,
        "vendorPots4": false,
        "vendorPots5": false,
        "vendorEnchR1": false,
        "vendorEnchR2": false,
        "vendorEnchR3": false
    },
    "professionSettings": {
        "fillOptionals": true,
        "autoPurchaseRes": true,
        "trainAssets": true,
        "skipPatrolTask": "AD&Lvl20",
        "smartLeadershipAssets": true
    },
    "generalSettings": {
        "refineAD": true,
        "keepOneUnopened": false,
        "openRewards": false,
        "runSCA": "free"
    },
    "consolidationSettings": {
        "consolidate": false,
        "minCharBalance": 10000,
        "minToTransfer": 50000
    },
    "taskListSettings": {
        "Leadership": {
            "taskSlots": "9",
            "taskProfile": "XP",
            "taskPriority": 2
        },
        "Jewelcrafting": {
            "taskSlots": "0",
            "taskProfile": "default",
            "taskPriority": "0"
        },
        "Alchemy": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Weaponsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Artificing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Mailsmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Platesmithing": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Leatherworking": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "Tailoring": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "BlackIce": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "WinterEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        },
        "SiegeEvent": {
            "taskSlots": 0,
            "taskProfile": "default",
            "taskPriority": 1
        }
    },
    "taskListSettingsManual": [
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        },
        {
            "Profession": "Leadership",
            "Profile": "AD",
            "fillAssets": 0
        }
    ]
}

**Comment by paladinpizza** [comment]
Missed noonereally's post above.  I fail at refresh ;)  Deleted my posts.  As soon as the script fails again, I'll post results.

@noonereally 
Do you mind posting or PM'ing the fix/patch?  I'm willing to guinea pig.

Edit:
OK, I see what you did.  I plugged the code in, will give it a 12 hour test run.  Prior to patching, it normally locked anywhere between 5mins-2hours.

**Comment by paladinpizza** [comment]
So far, so good here.  It's been running non stop with no issues (recovered gracefully from todays patch as well) after the inclusion of your code snippet.  5x toons at approx. 18 hours, no halts.

**Comment by noonereally** [comment]
Glad to hear, I'll close it for now then, if you encounter the problem again please re-open.
