### ISSUE TITLE
addProfile()

### ISSUE THREAD

**Issue by WloBeb** [Phr33d0m/NW-Profession-Bot#142]
As I have just proved in <a href=https://github.com/Phr33d0m/NW-Profession-Bot/pull/141>this</a> pull request addProfile() function is still too complicated (and maybe still bugged, even after this change).
I can rewrite it and add some checks, but I have to know the answer to some questions:
1. In which case typeof(profession) !=='string' ?
2. Is the typeof(base) ever different from 'string' or 'undefined'? 
3. What for is professionBase variable? In my opinion this function shouldn't create new profession and this is the only reason for professionBase variable existence. 
This code <pre><code>if(!definedTask[profession]) {definedTask[profession] = professionSet;}</code></pre> proves that author of this function supposes something different.
4. What for is profileBase variable?

I had once written addProfile() function from beginning, but it was not accepted. 
@dlebedynskyi wrote then, that this is not "JavaScript style". Maybe it was true, but my function was really cleaner and simpler....

**Comment by noonereally** [comment]
As I see it, the main reason to integrate /keep the option to add professions is to have the ability to have several profiles of the same profession.
Having leadership1 with 3 slots and profile X and leadership2 with 6 slots and profile Y should in theory allocate 3 and 3 slots. 
Similar to the leadership_xp that I've done at the beginning, but I've never tested it.

**Comment by WloBeb** [comment]
After consideration: first and fundamental question:
What is the <b>profession</b> variable passed to addProfile()???
If this is key in definedTask table, this means that custom profiles are buggy, because they stores definedTask[...].taskListName as profession name... In this situation addProfile() function was correct.

**Comment by noonereally** [comment]
I've reverted the  PR for now.
If it's the custom profiles should be fixed then then addProfile() ok for now.
And btw, 

> custom profiles are buggy

It's features. 

And in custom profiles taskName is actually taskListName (but changing it makes all the current custom profiles invalid so I just kept it as it is)

It's not definedTask index so the simple call to addProfile is probably not correct.

**Comment by WloBeb** [comment]
Everything is correct with one exception - you can't define custom profiles for Black Ice Shaping, Siege Event and Winter Event (most painfull is Black Ice for now). 
You shouldn't use taskListName property from tasklist but keys from definedTask.

**Comment by noonereally** [comment]
Why not set the keys to match the TaskListName?
I don't think the keys used anywhere at all. All the taskList have .forEach pr .filter searches so probably one should be added for the custom profiles, or make the keys match or indeed change addProfile()

**Comment by WloBeb** [comment]
I came up on the same ... and create pull request.
Problem is, we have redundant information in definedTask object...

**Comment by WloBeb** [comment]
As I said before:
 In my opinion addProfile() function shouldn't create new profession and this is the only reason for professionBase variable existence. 
This code <pre><code>if(!definedTask[profession]) {definedTask[profession] = professionSet;}</code></pre> proves that author of this function supposes something different.

But I leave this issue unchanged.
