### ISSUE TITLE
Prof level Tab empty

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#145]
hello, 
my prof lvl tab with my 24 toon have  lvl 0 on all profession.
last version work perfectly but this don't work

**Comment by djconnexion** [comment]
you can close this  i have found  why ....
my gateway are in french and the script is configruing  for english :'(

don't know why language of my gateway move in french

**Comment by noonereally** [comment]
Cool, I tried to look into it, but couldn't find any change.
