### ISSUE TITLE
4.1 Does not work for me

### ISSUE THREAD

**Issue by alorg** [Phr33d0m/NW-Profession-Bot#149]
Hi Since the start of 4.1 something seems to be not functioning properly. I have reverted to 4.0 as that still works fine. I have been ok using 4.0, BUT I like the new features that 4.1 has, so for me to be able to use it I hope that someone in the community know how to fix it, or even explain to me (I have next to none scripting knowledge) what could be going wrong.

This is the error I get on the console just after the 'Looking for empty slots' command is issued.

Uncaught TypeError: Cannot read property 'indexOf' of undefined  vm103:2113,

on opening the error I get the following list

processCharacter @ VM103:2113
loginProcess @ VM103:3575
(anonymous function) @ VM103:3458c.
(anonymous function) @ VM91:33

Hopefully this is enough info, if not I will submit any info required. Explanation on how to retrieve further info might have to be explain as well. 
I have tried the latest patch as well as the stable version and I get the same result in both instances.
This error only appears when I set the character to Manual Task allocation which is what I mainly use as I have complete control over what each slot creates.

Apart from that please keep up the amazing job you are doing and and all help would be much appreciated.

**Comment by noonereally** [comment]
Try it now please, I've updated it.

**Comment by alorg** [comment]
Working perfectly thanks for the fix and update

**Comment by alorg** [comment]
Well that was short lived LOL. found another instance of the same..

Uncaught TypeError: Cannot read property 'indexOf' of undefined vm906:2209

processCharacter @ VM906:2209
loginProcess @ VM906:3708
(anonymous function) @ VM906:3591c.
(anonymous function) @ VM891:33
