### ISSUE TITLE
Bug with Manual task allocation?

### ISSUE THREAD

**Issue by alorg** [Phr33d0m/NW-Profession-Bot#153]
I believe I found another bug with the manual task allocation. As i use this I will be submitting them to you guys who know how to fix it ; )
Looking for empty slots.
Uncaught TypeError: Cannot read property 'indexOf' of undefined vm1717:2209

processCharacter @ VM1717:2209
loginProcess @ VM1717:3708
(anonymous function) @ VM1717:3591.
c. (anonymous function) @ VM1690:33

**Comment by alorg** [comment]
Also found this error - which is appearing on the automated not manual setup.

Uncaught TypeError: Cannot read property '_lastSeen' of null                                    client.js:1

g.releaseOldLists @ client.js:1 

Although it does continue working when a task has finished and another one is required and does allocate the correct one.

**Comment by noonereally** [comment]
> Uncaught TypeError: Cannot read property '_lastSeen' of null client.js:1

Is probably a gateway bug, not related to the script directly.

**Comment by alorg** [comment]
OK thanks

**Comment by noonereally** [comment]
> OK thanks

Does it still get stuck ?

**Comment by noonereally** [comment]
As far as i can see it works, reopen if it doesn't.
