### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by gomsnothereman** [Phr33d0m/NW-Profession-Bot#157]
i have been getting these errors, come back and the page is there but the window where it shows your tasks/requirements/etc on the webpage, is just blank like it frozen... I checked the log and these are the only "errors" i see..

i can send you a saved version though if you would like.. just lemme know where to e-mail/send it..

Uncaught RangeError: Maximum call stack size exceeded

**Comment by gomsnothereman** [comment]
after playing the game some, i suspect this may be an issue with server side lag, or internet connectivity, and that was simply causing the script to jam up.

will keep an eye on it..

**Comment by noonereally** [comment]
Sometimes there is a weird gateway bug where it wont recognize the main worker it puts in the task (not the optional) 
And you can't activate the task unless you remove the worker and select it again. Unfortunately it is a gateway issue, though there is a counter to prevent it from killing the script and instead reloading the page so it's weird you got the stack size error.

If you can search&replace your account name and chars to Char 1, Char 2 And paste it somewhere like pastebin.com I'll take a look.

**Comment by gomsnothereman** [comment]
I replaced account name and char names.. (did char 7 twice on accident.. doh..) anyways here are 3 logs 1 from each time i found the script frozen.. it was always after it selected a task.. it would just be black in the middle (no spot to put resources/etc) but an F5 would fix it.. I think often it had been stuck for quite awhile, when i restarted it MOSt of the tasks would be finished on all the characters (except the 24hr ones)

http://pastebin.com/0bDtUfU8

**Comment by Phr33d0m** [comment]
This seems to be caused due to lag. Not sure if we can do something here.

**Comment by gomsnothereman** [comment]
most likely just a fluke then on my end/link/their end somewhere... i run both rotten_minds on one account and githubs(this one) on another account.. and sometimes i see both frozen, but past 36 it had only been this one (3 times).. so wasn't sure if it was a lag/response issue or something recently changed or as i 1st suspected it was something unique to 1 character..

thanks for looking at it however :)

**Comment by Phr33d0m** [comment]
It's the same bot... "_Rotten_mind's_" is just an older core version with some mods here and there, so I'm 99% sure both have the same issue.

If you happen to get a more verbose debug log (like what code line fails) please reopen this bug. You can get more verbose log if you have chrome's devtools opened when the issue happens.

**Comment by noonereally** [comment]
Thanks for posting the log. But as phr33d0m said, unfortunately the interesting part was trimmed, so can't really help. I saw this happen one time, but not sure why and couldn't reproduce.
Sorry it came out to nothing.
