### ISSUE TITLE
Show number of celestial coins in resources tab

### ISSUE THREAD

**Issue by NameTakenAgain** [Phr33d0m/NW-Profession-Bot#165]
With 43 characters it is quite a hassle going through all your characters to check if it time to buy a new coffer or empty the bags... The celestial coins and the number of free bag slots aren't real resources, but it would be useful to be able to track them as the other resources. Would it be hard to add?

**Comment by Phr33d0m** [comment]
With v4.2 you can see the number of free bag slots for each character at the Resource Tracker tab. The number of celestial coins might be a nice addition.

**Comment by noonereally** [comment]
Should be in the same group as currencies (gold, ad), and probably will be best to be added into the same part in statistics structure.

**Comment by gomsnothereman** [comment]
do you use a invoking bot?? BigRedBrents can be setup to buy the items with the celestial coins for you.. works great! (though you can't have it buying multiple types of bags.. just 1 type though you can make different versions/edits to buy each type as you want..)

**Comment by NameTakenAgain** [comment]
I have written a Python script that invokes for me, but it is a bit fragile. For some reason it wouldn't match the "vault of piety" png for all characters. Just for some. I'll check out BigRedBrent's invoker and see if it does a better job.

Thanks for the tip.

**Comment by noonereally** [comment]
Added the celestials count.
