### ISSUE TITLE
forget  summer event prof 

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#166]
as titl say  there is no summer  event prof.... i think it's a forget  :)

**Comment by noonereally** [comment]
Not sure if there is anything good to make there.

**Comment by djconnexion** [comment]
like the winterfestival you can create hero feast : Event_Summer_Tier3_Sunite_Altar

**Comment by noonereally** [comment]
I've added one from a question that was asked here:
https://greasyfork.org/en/forum/discussion/5028/x

**Comment by djconnexion** [comment]
ok thx
