### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by noonereally** [Phr33d0m/NW-Profession-Bot#168]
@Phr33d0m 
There are several branches now, maybe some can be removed? 
The deferred one is interesting and maybe someone will continue the work at some point.
I think the rest was already committed or not relevant.

**Comment by Phr33d0m** [comment]
At this point we can delete all branches. I have no idea what has been done into the deferred branch but if you think it's worth keeping then I won't remove it. 

There's also 1 branch that's yours. Delete it if you don't need it anymore.
