### ISSUE TITLE
Add Alchemy unstable potions to vendorProfResults

### ISSUE THREAD

**Issue by Evpok** [Phr33d0m/NW-Profession-Bot#169]
Those byproducts of alchemy fill the inventory, apparently for nothing and could be vendor as junk, or given a specific option if someone actually uses them for something.

**Comment by Phr33d0m** [comment]
I'm particularly fond of those potions so you might as well just send them to me ;-). Anyways, it's still profession crafted junk so it might be a good option to link those potions to the vendorProfResults option.

**Comment by Phr33d0m** [comment]
Added as per #170
