### ISSUE TITLE
task failure, not detect three task started

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#17]
From Greasy, mostly it happen "Leadership destroy enemy camp" and easy resolve is "Reload", detection for this error?

---

t4k 
12:30AM  ChromeFlag
Some times script try do 4 same tasks, gateway denied, but he tries and tries...
May be this happend after pause/unpause script.
After restart browser works fine.

---

**Comment by RottenMind** [comment]
This known common failure with, "destroy enemy camp", "collect taxes",

---

 Failed to resolve item requirements for task: Leadership_Tier3_20r_Master1
VM25880:1327 Finding next task
VM25880:1254 Leadership is level 20
VM25880:1255 createNextTask 11 2
VM25880:1258 Searching for task: Leadership_Tier3_20r_Master3
VM25880:1347 Could not find task for: Leadership_Tier3_20r_Master3
VM25880:1327 Finding next task
VM25880:1254 Leadership is level 20
VM25880:1255 createNextTask 11 3
VM25880:1258 Searching for task: Leadership_Tier3_20_Destroy
VM25880:1287 Task Found
VM25880:1615 Clicked item
VM25880:1301 Items Populated
VM25880:1306 Clicking Start Task Button

---

It is really hard replicate because it is caused by gateway, 

---

< div class="input-field button epic">
< div class="input-bg-left"></div>
< div class="input-bg-mid"></div>
< div class="input-bg-right"></div>
< button onclick="client.professionStartAssignment('Leadership_Tier3_20_Destroy')"> Start  Task</button>
< / div >

---

Button "Epic" + "start assigment"  should be disabled after three "Destroy Enemy Camp" is started but they are NOT, so script see only buttons what are enabled and stays infinite loop until Gateway reloads.

Suggestion add somekind detection if same task is tried start XX times and reload script, can be additional function like "Inventory_bagspace()" , what sells crafted items untill inventory has X free slots.

Loop disappear after "Ctrl-F5" 

ps. I did this kind extrenal "loop detection" for  APBI, it just look log window and load last 10x entry to array, check if string match x times , check program path by PID and restart bot process. SAme script keeps 10x accounts running all the time... but not open Rewards, sell junk, sell crafted and NOT have source code + devlopment!!! :(

**Comment by mac-nw** [comment]
What i think happens is that there is a lag between the gateway client and server which delays the data on the client to update. Probably the server is lagging at sending the client updated profession info and the client has no clue that the there is already 3 tasks assigned or that a task is available or that the task is started etc...

**Comment by Phr33d0m** [comment]
@mac-nw it is indeed caused by lag. If I fire up my torrent program which eats _110%_ of my bandwith I can reproduce the issue pretty easily. Is there any workaround like what @RottenMind said about counting the already assigned tasks and avoid stucks?

**Comment by mac-nw** [comment]
If the client and server don't sync up then i'm not sure there is much you can do. You can't be sure any commands get through from client to server and vise versa :/

It might be possible to put a callback on the model update and perhaps just put the script into a waiting state. I've seen some methods on the model that suggest it is possible but i've not had a chance to play with it.

**Comment by RottenMind** [comment]
Sorry to say,
- lag is counted out(on my test)
- script continues 1 minutes - 2h 29min  if no reload applied

If there is way count actions "start task" per character per taskname...
- max. count "start task" 9, but if asset/selection failures are counted in ?

So it stays this loop hours if "Auto Reloload" is enabled, "infininite" if page dont reload, xD.

## So any detection method what is applied has hours to detect this "gateway" based glitch, xD xD.

_Simple "Reload per hour", works if you have few toons, but with 30 + toons it might cause bad effect, because rotation might never reach last toon, but reload per hour is better than "infinite loop" and "releoad per 3 hours" fix this "gateway" glitch 8x per 24hours._

If this "gateway" glitch can be reproduced with torrent client, then its good to try find way to detect "infinite loop" if this cant be detected, then can simply say that, -"some GAteway_client -based errors cause Bot stay infinite loop (Stuck)" and "Enable Reload" solve issue.

I think this issue is similar with "Extra asset failure", in some rare cases extra asset selection cause samekind situation.

**Comment by RottenMind** [comment]
WloBep, corrected this.
