### ISSUE TITLE
Refine 7 tab

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#173]
hello, 
first of all thx for this news tab.
i see some change in my different day when a day was move.

exemple  :  day -2 to -3 369K to 343K
same for -1 to -2 500K to 497K
can you explain me why this change and in a character there is a 0 on - 3 day when it is in -2 day  there his a 15K+.

is this tab work as the refine tab and the R.today colums and reset each day at the reset time of RD refine ?

**Comment by noonereally** [comment]
I started to write and explanation, but I'm going to fix the per char processing when I have time so it will be clearer and more accurate. 

The short explanation the data is accurate at the end of the day (server reset days) when the first column doesn't have `0*`

---

The tab shows how much each char refined in previous days. ( 0 is today - ongoing, -1 yesterday and so on) 
The issue you probably see is that the chars updated one by one when they are processed and not moved immediately on day reset. 
So if you have two chars and lets say one refines 24k and has backlog and the other around 15k 
you will see:

At the beginning of  a day 

| Chars | 0 | -1 | -2 | -3 |
| --- | --- | --- | --- | --- |
| C 1 | 24k |  |  |  |
| C 2 | 0 |  |  |  |

After some profession finished:

| Chars | 0 | -1 | -2 | -3 |
| --- | --- | --- | --- | --- |
| C 1 | 24k |  |  |  |
| C 2 | 6k |  |  |  |

End of the day:

| Chars | 0 | -1 | -2 | -3 |
| --- | --- | --- | --- | --- |
| C 1 | 24k |  |  |  |
| C 2 | 15k |  |  |  |

Next day let say the first one to be finished with a profession is char 2,
So his data will be moved to the next day:

| Chars | 0 | -1 | -2 | -3 |
| --- | --- | --- | --- | --- |
| C 1 | 0* | 0 |  |  |
| C 2 | 2k | 15k |  |  |

And later:

| Chars | 0 | -1 | -2 | -3 |
| --- | --- | --- | --- | --- |
| C 1 | 24k | 24k |  |  |
| C 2 | 2k | 15k |  |  |

**Comment by djconnexion** [comment]
ok i understand now how they have some change.
thx a lot.

**Comment by Phr33d0m** [comment]
Please use the greasyfork forum for questions.
