### ISSUE TITLE
Leaving slots open 

### ISSUE THREAD

**Issue by gomsnothereman** [Phr33d0m/NW-Profession-Bot#181]
I have run into a recent issue, i see/found out that alchemy would not do gathering tasks to build up gold to buy certain needed resources, so i set the characters to be 9 slots alchemy medium rating, and 9 slots artifice, bulk gathering on low.. I noticed it is leaving most (if not all) of the slots "open" on some characters, and i can't seem to figure out why.. any suggestions?

---

went back and tried setting alchemy to low priority too, didn't seem to make a difference.... is there a way to force the script to "update" a certain character?? (that way i can watch the log when it is on the ones with open slots..)

**Comment by noonereally** [comment]
You can reset the time in the "SCA & Visits" tab.
Also do you have the artificers or have the train assets on ?

**Comment by gomsnothereman** [comment]
Yes i do have it set to train assets..
hmmm i should have at least ONE artificer that can do the highest level mass gathering (they were all up to 16 or so before i set them to do mass gathering just to build up materials i can sell to help out alchemy) .. didn't consider that will it not train/hire artificers to do mass gathering if the character is SET to do mass gathering?

---

Well i know what is wrong.. but no clue WHY, it wants to buy "coal" before doing mass gathering(s) and if it can't buy ANY, it skips all the tasks under mass gathering for artificing (this also seemed to affect jewelcrafting too tried it)... dug through the code some myself, and umm honestly dunno why it thinks that is a requirement for mass gathering...

**Comment by HenryLoenwind** [comment]
not sure if I understand your problem correctly, but:

(a) The script will skip mass production tasks for profiles without useMassTask flag == true. That is all tasks that have a name that starts with Batch, Mass, Deep or Intensive.

(b) I see no mass gathering on Artificing and Jewelcrafting, just mass refining/crafting. Do you use custom profiles? Or did you confuse gathering and refining/crafting? Because the refining/crafting tasks on lvl 14 and 21 do use coal.

**Comment by gomsnothereman** [comment]
oh my goodness.. i am such an idiot.. you are 100% right i mixed up refining and gathering ughhhhh.. THAT explains why i couldn't see in the code why it was doing that..

i am going to go dig an hole and hide my head in it now.. i feel like a 100% idiot :)

**Comment by gomsnothereman** [comment]
well now that i made a complete fool of myself, here is a custom profile if someone DID want to do mass gathering on say Aritifcing, if you wanted to do it on any other profession just change the names from artificing to.. whatever profession i believe they are all the same syntax beyond that :)

{
    "profileName": "mass gathering",
    "isProfileActive": true,
    "useMassTask": true,
    "level": {
        "0": ["Artificing_Tier0_Intro_1"],
        "1": [ "Artificing_Tier1_Gather_Basic_Mass"],
        "7": [ "Artificing_Tier2_Gather_Basic_Mass"],
        "14": ["Artificing_Tier3_Gather_Basic_Mass"],
        "21": ["Artificing_Tier4_Gather_Basic_Mass"]
    }
}
Reason i was doing this was it would level up artificing (slowly) and let me every few days sell all the gather products, to make some cash to help level up alchemy or other professions..

Well posted this too quick, oddly it gets hung trying over and over to add more assets to the gathering, before i guess timing out (after about 15 tries), if it HAS 4 assets it works fine but if it does not it adds what it can and gets hung on the last one.. any suggestions??

**Comment by BigRedBrent** [comment]
I could just add a default mass gathering profile to artificing.

**Comment by gomsnothereman** [comment]
not sure why it is glitching sometimes for me, i paused it an d backed out of it one time when i twas trying to start, and it didn't have the crafter to start the gathering, it is almost like it started the next one so fast the site hadn't yet acknowledged some were in use, so it kept trying to hit "start" and it wouldn't..

There is nothing special about artificing that i am doing gathering with it.. just figured it was an easy way to get up to 20 without worrying about inventory filling up..

**Comment by noonereally** [comment]
> it is almost like it started the next one so fast the site hadn't yet acknowledged some were in use, so it kept trying to hit "start" and it wouldn't..

Did you use the reset times ? If you did try reloading the gateway after you reset the chars you want. (refresh the page)

**Comment by gomsnothereman** [comment]
hmmm what reset times? (obviously i must of not used em :) )

**Comment by Phr33d0m** [comment]
Closing as per #247
