### ISSUE TITLE
Vendor options

### ISSUE THREAD

**Issue by Pazarion** [Phr33d0m/NW-Profession-Bot#187]
I all time have problems with OverBags, version 4.4.2 helped a lot but need add some modification. I Offer add possibility to sell [Lesser Mark of Potency][Lesser Mark of Power][Lesser Mark of Stability][Lesser Mark of Union][Minor Power Stone][Minor Union Stone][Minor Stability Stone] in this way we can clean 14 inventory slots ( bound and unbound items). + Due- to SCA runs I have unidentified useless items in inventory so can you add possibility to sell this items automatically too.

**Comment by Pazarion** [comment]
Cant pray du to OverBags need help.

**Comment by Phr33d0m** [comment]
#174
