### ISSUE TITLE
why in profession you have  the "name of prof_TierX_Refine_Special"

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#191]
hello, 
as the title say  this sort  of task need a special bag  you need to buy in AH on take in profession pack.

so can you explain why you put this task  ?

for exemple  in alchemy  : "Alchemy_Tier1_Refine_Special"

with this task bot send message to buy the bag  needed.

best  regards

**Comment by Phr33d0m** [comment]
It's just one of the many in the list. If you have the item it'll do that task, if you don't have the item it'll skip to the next task.
