### ISSUE TITLE
The Winter Festival 

### ISSUE THREAD

**Issue by Aalafalot** [Phr33d0m/NW-Profession-Bot#197]
Will you be updating the Winter Festival?   It seem to be not working.

**Comment by Decorius** [comment]
My script was not running after Winter Event started, I found that I needed to change any instance of "WinterEvent" to case match "Winterevent".  After I did this the script resumed functioning.  Although the script was now running again, it is not picking up Winter Event tasks and executing them until I went back and update the profile to assign a slot to the Winterevent.  I had assigned those prior to changing the script to case match, but when I did the change it wiped those values for Winterevent from the profile.  All working for me now.

**Comment by Aalafalot** [comment]
Which one is your script?   This script is not working!

**Comment by Decorius** [comment]
I am currently using RottenMind's version (an update of Bunta/Mustex) version 1.10.07.04
https://greasyfork.org/scripts/7061-neverwinter-gateway-professions-robot/

**Comment by Aalafalot** [comment]
I switch to that one.   I prefer NW-Profession-Bot due to more options.
