### ISSUE TITLE
Forgehammer of Gond

### ISSUE THREAD

**Issue by imit8r** [Phr33d0m/NW-Profession-Bot#199]
Howdy all, love what you have done with this thing.

My question/problem revolves around the Forgehammer of Gond.  I have a legendary one, and plan on upgrading it, but the upgrade isn't really relevant right now.  I am trying to figure out how to add it as a useable Asset, since it has a higher % for success.  I tried editing the script, where the assets are (both places) using the item info from a different script from github.  Any help here would be amazing!

Thanks again.

**Comment by noonereally** [comment]
Haven't touched this for a while, but I can look into it.
Can you tell me what you see now, other assets selected instead ? workers? 
Looks like the legendary / Mythical assets already in the code.

**Comment by noonereally** [comment]
I've added a pull request for this change:
https://github.com/noonereally/NW-Profession-Bot/blob/master/main.js

Requires testing.

**Comment by imit8r** [comment]
Thanks, how do I help with testing now?  Just download that new main.js?

**Comment by Titi211** [comment]
hello all

is it working with hammer of gond ?

I have one and i can't use with the script

thx for your job

**Comment by noonereally** [comment]
Did you check the gond checkbox in the right profession ?
Are you using the regular task or manual ?
And what it does ? It adds regular tools instead?
