### ISSUE TITLE
Infinite loop with latest changes

### ISSUE THREAD

**Issue by Phr33d0m** [Phr33d0m/NW-Profession-Bot#20]
Hey @mac-nw, something in the changes after 17th january broke the thing. The bot collects the rewards but then doesn't fill the spots and causes infinite loops like this one:

```
 No date found for Black Rose, switching now.
VM1025:2247 Next run for Black Rose in 1 seconds.
VM1025:1367 All task counts assigned
VM1025:1460 No next finishing date found!!
VM1025:1377 Black Rose's Astral Diamonds: 7990
VM1025:2185 Character does not have minimum AD balance to do funds transfer. Skipping Zex Posting..
VM1025:2196 Opening Rewards
VM1025:2935 Attempting to vendor selected items...
VM1025:2217 Switching Characters
```

**Comment by RottenMind** [comment]
I updated just few minutes ago and it works well, latest build.

Buys armor/weap too.

**Comment by noonereally** [comment]
Maybe the settings task numbers were not reset, try clearing them and setting numbers. There are new task names so the saved settings are not valid and the defaultTaskList should be loaded.

**Comment by RottenMind** [comment]
I got it stuck too, need test reload.

**Comment by mac-nw** [comment]
With the merge from noonereally, you have to Clear/Save tasks to reset them to the new task lists. We'll have to figure something out here when publish this..

**Comment by RottenMind** [comment]
Yes, it needs "Reset action"... and Im out vodka, :( .

**Comment by Phr33d0m** [comment]
Oh I see... We should write this down somewhere. That'll be quite a PITA for the guys with 50 toons, ha!

Also, @mac-nw could we keep the master branch as stable as possible? We should make a 'dev' branch that'll be our test zone where we'll merge the pull-reqs and do stuff that need to be tested. Once stuff tested we'd move it to the master branch. Sounds good to you?

**Comment by noonereally** [comment]
btw why the taskList is saved as a setting into settings array and not used straight from taskListDefault ?
And the reset need / looping is due to mailsmithing / platesmithing name change and not related to leadership, so worst case can change it back.

**Comment by RottenMind** [comment]
One account is stuck, not selecting leadership task, 2 characters, no other professions running.

Second account works fine, 6x character, mixed leadership + other profession leveling.

Switching tasklist is asked feature but it must be done different way.

I try look changes and test what change makes that non-working account/browser work again.

**Comment by RottenMind** [comment]
You can replicate bug, (works with leadership only!!!?)
1. Select "Train Assets"
2. make sure that you dont have all needed assets
3. Reload script
4. Script works as intended but it stucks on "Train Assets" after it used all available assets. 
5. Weird, with other Professions no stuck.
   Why this happens, IDK.

**Comment by noonereally** [comment]
I tried the above to replicate on the Fork I have already installed and the "Hire A Mercenary" started as it should.
I will try the master branch later.

About task in general, I think once selects added into the settings gui the different task lists can be made as 'profiles' for each profession, and in a nested object in the code and not like now. 
This will also allow more options per profile, like: 'active / not active', 'prioritize tools or assets'

**Comment by RottenMind** [comment]
About "replicate Bug", I can do it again but I need reinstal script so I have fresh untouched script, testing "Rare" task stuff now.

Check "Asset selection" section, will "Task list" change affect that?

**Comment by Phr33d0m** [comment]
Guys, this issue was about the clear/save tasks as @mac-nw [already said](https://github.com/Phr33d0m/NW-Profession-Bot/issues/20#issuecomment-70581430).

Please create new issue(s) with the specific infinite-loop/getting-stuck/whatever you've found (as there seems to be more than 1 case) so we can keep track of this easier.

**Comment by RottenMind** [comment]
Not sure name of issue, but "train asset stuck" still exist on current build and is reported.
