### ISSUE TITLE
The Winter Festival - Adding Couple of Options 

### ISSUE THREAD

**Issue by Aalafalot** [Phr33d0m/NW-Profession-Bot#203]
Is there any chance to add specific options into winter fest to do following task?

Open Sickly Marimo
Open Illuminated Marimo

If none exist, go to 
Fish for Light Pods

And/or create a task to just make 

Fish for Light Pods

**Comment by ghost** [comment]
I hope this helps.

You can comment/uncomment/delete task lines in profile.
You can add profile directly in your script-file.

``` javascript
    addProfile("Winterevent", {
        profileName: "RP (Bound)",
        isProfileActive: true,
        level: {
            3: [ /*"Event_Winter_Tier1_Heros_Feast","Event_Winter_Tier1_Lightwine","Event_Winter_Tier1_Sparkliest_Gem","Event_Winter_Tier1_Mesmerizing_Lure",*/
                    "Event_Winter_Tier3_Refine_Ringoflights",
                    // "Event_Winter_Tier3_Refine_Winterkillemblems",
                    "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                    "Event_Winter_Tier1_Refine_Marimo_Sick", //Open Sickly Marimo
                    "Event_Winter_Tier1_Simril_Refinement_R2", //x4 Lumen Synthesis
                    "Event_Winter_Tier1_Refine_2", //4-1 2 Cluster
                    // "Event_Winter_Tier1_Refine_2_Mass", //32-8 30 Cluster
                    "Event_Winter_Tier1_Refine", //4-2 2 Mote
                    // "Event_Winter_Tier1_Refine_Mass", //30-16 30 Mote
                    // "Event_Winter_Tier1_Gather_3" //Lure
            ],
        },
    });
```

You can also add it in script menu via "Custom Profiles".

``` javascript
{
    "profileName": "Craft Bright Lumen",
    "isProfileActive": true,
    "level": {
        "3": ["Event_Winter_Tier3_Refine_Ringoflights",
        "Event_Winter_Tier1_Refine_Marimo_Illuminated",
        "Event_Winter_Tier1_Refine_Marimo_Sick",
        "Event_Winter_Tier1_Simril_Refinement_R2",
        "Event_Winter_Tier1_Refine_2",
        "Event_Winter_Tier1_Refine"]
    }
}
```

**Comment by Aalafalot** [comment]
I decided to use the custom profile.  I hit imported the script into Winterevent.    It created the "Craft Bright Lumen" profile under "Default" Profile option.

I look at the script, it imported this entire script.     Very Strange.    But, under Import option, it has the the custom script.   It keep running this entire larger script. 

[
    {
        "profileName": "Craft Bright Lumen",
        "isProfileActive": true,
        "level": {
            "0": [
                "Event_Winter_Tier0_Intro"
            ],
            "1": [
                "Event_Winter_Tier1_Rankup",
                "Event_Winter_Tier1_Refine",
                "Event_Winter_Tier1_Gather"
            ],
            "2": [
                "Event_Winter_Tier1_Rankup_2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Gather_2"
            ],
            "3": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "4": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "5": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "6": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "7": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "8": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "9": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "10": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "11": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "12": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "13": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "14": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "15": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "16": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "17": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "18": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "19": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "20": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "21": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "22": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "23": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "24": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ],
            "25": [
                "Event_Winter_Tier3_Refine_Ringoflights",
                "Event_Winter_Tier1_Refine_Marimo_Illuminated",
                "Event_Winter_Tier1_Refine_Marimo_Sick",
                "Event_Winter_Tier1_Simril_Refinement_R2",
                "Event_Winter_Tier1_Refine_2",
                "Event_Winter_Tier1_Refine"
            ]
        }
    }
]

**Comment by noonereally** [comment]
Custom profiles have some auto completions to help the user make full profiles with very little changes. And especially if you use a base profile.

you can find an explanation here (not 100% sure if up to date):
https://greasyfork.org/en/forum/discussion/5248/x

In any case, I don't see any problem with what you have, it took the 1,2 levels from the base and put the level 3 as you wanted it, the copy until 25 wont change anything, and it's done so the regular professions will keep working (up to level 25) if for example you want some low level task keep on going (like gathering) for all levels. 

Most of the profiles in the code are also 'expended' in the same way, most of alchemy, gathering profiles and others.
