### ISSUE TITLE
Assets Options

### ISSUE THREAD

**Issue by ghost** [Phr33d0m/NW-Profession-Bot#204]
I would like to see more options for the assets.

Drop down menu per character, per task:
- Do not fill
- Default (people/tools)
- People (white to purple)
- People (purple to white)
- Tools

And I also have a question about:

``` javascript
// 0 - default, 1 - do not fill, 2 - people (white to purple), 3 - people (purple to white), 4 - tools
var charSlotsFillAssetsOptions = ['default', 'Do not fill', 'c', 'people (purple to white)', 'tools'];
```

is it work?

Can u guys git reset hard to 17fac48369bb65d6d3efd850f335a41c23cf224a and recommit new additions;
eef93b43d414ce59771e6b88f1c2847ffcaf2832 07d68d18c32694bcb46c843de1ae6076d9f063b4 it burn my eyes;
thank you.

**Comment by FabrizioDonnarumma** [comment]
Exact same question

**Comment by FabrizioDonnarumma** [comment]
Same request

**Comment by Asdrubale1** [comment]
I have the very same question.
I also cannot understand if that var is called at all.

**Comment by noonereally** [comment]
It is not called.
