### ISSUE TITLE
mastercraft

### ISSUE THREAD

**Issue by Titi211** [Phr33d0m/NW-Profession-Bot#205]
Hello all
Thanks for all work you make for this tool
I would like to know if its possible to make mastercraft tasks with this tool ?

i'm working on alchemy

i would like to make this task (professions-tasks/Alchemy/Alchemy_Masterwork_Oilofvitriol) automatically

that task need also to fill slots with purple tools

thx in advance

**Comment by noonereally** [comment]
What alchemy level this task is ?

**Comment by Titi211** [comment]
its a lvl25 mastercraft

**Comment by noonereally** [comment]
You can added it as a custom profile, go to Custom Profiles tab, select 
Task name: Alchemy
Base Profile: default

Paste:

```
{
    "profileName": "Oil",
    "isProfileActive": true,
    "level": {
        "25": ["Alchemy_Masterwork_Oilofvitriol"]
    }
}
```

And click import, you should see "Oil" profile in alchemy.

**Comment by Titi211** [comment]
thank for your help

but need a rank 3 with purple tools

your profile make only 1 tool in place of 3

**Comment by noonereally** [comment]
Tools and the optional slots are not in the profiles, you need to have the `Fill Optional Assets` Option under `Professions` enabled for it to fill the optional slots.

**Comment by Titi211** [comment]
hello

thank for your patience

fill optional asset is enabled but its dont fill optionnal slots after the first tool and i need 3

**Comment by Titi211** [comment]
Correction ; after a restart its works

thanks for your help

U are the best
