### ISSUE TITLE
Alchemy Feature Request!   

### ISSUE THREAD

**Issue by Aalafalot** [Phr33d0m/NW-Profession-Bot#206]
Adding the following to items to alchemy choices.  These 2 potion sell well too especially when Elemental Aggregate get to expensive on AH.
Major Flask of Potency
Major Flask of Protection

**Comment by griley4** [comment]
You can create custom profiles for any crafting task you want. the option is under the "custom Profiles" 
tab. i'll paste a custom profile here for Major Potency which i wrote. Please use as an example, comes with no guarantees.  
Task Name : Alchemy
Base Profile : Default
Profile :

>  {
>     "profileName": "Potency Major",
>     "isProfileActive": true,
>     "level": {
>         "0": [
>             "Alchemy_Tier0_Intro_1"
>         ],
>         "1": [
>             "Alchemy_Tier1_Experiment_Rank2",
>             "Alchemy_Tier1_Experimentation_Rank1",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "2": [
>             "Alchemy_Tier1_Experiment_Rank3",
>             "Alchemy_Tier1_Experimentation_Rank2",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "3": [
>             "Alchemy_Tier1_Experiment_Rank4",
>             "Alchemy_Tier1_Experimentation_Rank3",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "4": [
>             "Alchemy_Tier1_Experiment_Rank5",
>             "Alchemy_Tier1_Experimentation_Rank4",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "5": [
>             "Alchemy_Tier1_Experiment_Rank6",
>             "Alchemy_Tier1_Experimentation_Rank5",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "6": [
>             "Alchemy_Tier1_Experiment_Rank7",
>             "Alchemy_Tier1_Experimentation_Rank6",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier1_Gather_Basic"
>         ],
>         "7": [
>             "Alchemy_Tier2_Experiment_Rank08",
>             "Alchemy_Tier2_Experimentation_Rank07",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "8": [
>             "Alchemy_Tier2_Experiment_Rank09",
>             "Alchemy_Tier2_Experimentation_Rank08",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "9": [
>             "Alchemy_Tier2_Experiment_Rank10",
>             "Alchemy_Tier2_Experimentation_Rank09",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "10": [
>             "Alchemy_Tier2_Experiment_Rank11",
>             "Alchemy_Tier2_Experimentation_Rank10",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "11": [
>             "Alchemy_Tier2_Experiment_Rank12",
>             "Alchemy_Tier2_Experimentation_Rank11",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "12": [
>             "Alchemy_Tier2_Experiment_Rank13",
>             "Alchemy_Tier2_Experimentation_Rank12",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "13": [
>             "Alchemy_Tier2_Experiment_Rank14",
>             "Alchemy_Tier2_Experimentation_Rank13",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier1_Refine_Basic",
>             "Alchemy_Tier2_Gather_Basic"
>         ],
>         "14": [
>             "Alchemy_Tier3_Experiment_Rank15",
>             "Alchemy_Tier3_Experimentation_Rank14",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "15": [
>             "Alchemy_Tier3_Experiment_Rank16",
>             "Alchemy_Tier3_Experimentation_Rank15",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "16": [
>             "Alchemy_Tier3_Experiment_Rank17",
>             "Alchemy_Tier3_Experimentation_Rank16",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "17": [
>             "Alchemy_Tier3_Experiment_Rank18",
>             "Alchemy_Tier3_Experimentation_Rank17",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "18": [
>             "Alchemy_Tier3_Experiment_Rank19",
>             "Alchemy_Tier3_Experimentation_Rank18",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "19": [
>             "Alchemy_Tier3_Experiment_Rank20",
>             "Alchemy_Tier3_Experimentation_Rank19",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "20": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "21": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "22": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "23": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "24": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ],
>         "25": [
>             "Alchemy_Tier3_Potency_Potion_Major",
>             "Alchemy_Tier2_Aquaregia",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier2_Refine_Basic",
>             "Alchemy_Tier1_Refine_Special",
>             "Alchemy_Tier3_Refine_Basic",
>             "Alchemy_Tier3_Gather_Basic"
>         ]
>     }
> }
