### ISSUE TITLE
profileName

### ISSUE THREAD

**Issue by griley4** [Phr33d0m/NW-Profession-Bot#208]
Hello All,

Thanks for this great tool, i especially like the flexibility that custom profiles give me. 
I have just two questions, i setup a custom profile like this

> [
>     {
>         "0": {
>             "profileName": "G RPdc Vlcg",
>             "isProfileActive": true,
>             "level": {
>                 "0": [
>                     "Leadership_Tier0_Intro_1"
>                 ],
> .....

it continues correctly and is imported just fine, but the profileName in the dashboard is now "Add profile name" instead of "G RPdc Vlcg".

My second question is, when i get to level 17, it doesn't take my changes into effect.

> ```
>         "17": [
>           "Leadership_Tier3_17_Deliver",
>             "Leadership_Tier3_13_Patrol",
>             "Leadership_Tier2_9_Chart",
>             "Leadership_Tier3_13_Training",
>             "Leadership_Tier1_5_Explore",
>             "Leadership_Tier1_4_Protect",
>             "Leadership_Tier2_7_Training"
>         ],
> ```

this is my block for 17, i added Deliver before the rest of the tasks, however the script is still loading in Patrol first.  i have tried restarting my browser like suggested in some other posts.
Any insight would be helpful,

Thanks in advance

**Comment by noonereally** [comment]
I think your syntax is incorrect, you have a `"0": {` at the start, it shouldn't  be there.

```
{
    "profileName": "G RPdc Vlcg",
    "isProfileActive": true,
    "level": {
        "0": ["Leadership_Tier0_Intro_1"],
....
        "17": ["Leadership_Tier3_17_Deliver",
            "Leadership_Tier3_13_Patrol",
            "Leadership_Tier2_9_Chart",
            "Leadership_Tier3_13_Training",
            "Leadership_Tier1_5_Explore",
            "Leadership_Tier1_4_Protect",
            "Leadership_Tier2_7_Training"]
    }
}

```

It may be related to both things you see, if not, enable the debug option in script options and press ctrl+shift+j in chrome, it should show you the console,  paste here (with char names removed) the part when it tries to select the task, you should see sometihng like 

```
Leadership level xx
CreateNextTask xx x
Searching for  taskname
```

**Comment by griley4** [comment]
Wow! that solves both problems. I didn't even see that typo in my copy pasta :(

Thanks for the second pair of eyes! great script you've got here.
