### ISSUE TITLE
Switch between languages

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#21]
English is main language, but some users want use their own and RU Gateway are different.

Just not sure what is best method switch between options, ideas are welcome

---

var enabledButton = $("div.footer-body > div.input-field.button:not('.disabled') > button:contains('Start Task')");
var enabledButton = $("div.footer-body > div.input-field.button:not('.disabled') > button:contains('Aufgabe beginnen')");
var enabledButton = $("div.footer-body > div.input-field.button:not('.disabled') > button:contains('Начать поручение')");

---

var buttonList = $("h3:contains('Optional Assets:')").closest("div").find("button");
var buttonList = $("h3:contains('Optionale Ressourcen:')").closest("div").find("button");
var buttonList = $("h3:contains('Дополнительные средства:')").closest("div").find("button");

---

$("div.footer-body > div.input-field.button > button:contains('Back')").click();
$("div.footer-body > div.input-field.button > button:contains('Zurück')").click();
$("div.footer-body > div.input-field.button > button:contains('Назад')").click();

**Comment by RottenMind** [comment]
Tested and only,
- Back
- Start Task

, worked properly if I switched language to DE, RU Gateway needs account what I dont have.

Optional Asset option acted weird way,
- selected one asset and exit, Buntas orig. asset selection (lang. DE)
- selected no assets, Current asset selection (lang.DE)

If language was selected as DE and Profession Leatherworking needed "Einfache Pelze sammelnt" (simple pelts curing), bot started "Mass curing pelts" task, some filters should prevent it, but it did same action again, xD.(seems bot not like other language) 

Other options worked without problems or I did not catch errors they made.

So adding language option other than EN will not work well with current build and adding that option is not necessary for those who not use RU Gateway for RU Gateway users language option if added will give limited Automation, if some changes are not made to "Asset Selection" buttons detection/clicking and if language switch option is added it not interfere Bot other functions if Gateway is EN.

I will give test version to some users who use RU Gateway and look if I have time made account to RU server(dont know how to do it).

ps. I do not know how many grammar error that  text contains, but maybe its not issue here, xD.

**Comment by Phr33d0m** [comment]
I'll add a TODO section in the readme. This is some of the things we should remove/replace/fix in the future.
- Replace any string-based jquery selectors in favor of making the bot work with any language (not only english)

**Comment by RottenMind** [comment]
jeps, that sounds just what I wanted, but I lack JAVA -skill to do that or even say what you did say.

...it is just weird that "Start Task" works fine, but hopefully those strings can be replaced, then can ask "Tooltips" translate, few volunteers are allready nearby, ;).

**Comment by RottenMind** [comment]
Well, it work with those "strings" now, it seems that whole script has has 4 place where you need change and it work, :).

**Comment by mac-nw** [comment]
@RottenMind Try out the fix please

**Comment by RottenMind** [comment]
looks good, poor RU gateway acc. says now  "спасибо", ;)

Need full testing, but spezial issues are not language based.
