### ISSUE TITLE
XMLHTTPREQUEST

### ISSUE THREAD

**Issue by djconnexion** [Phr33d0m/NW-Profession-Bot#210]
i see this  in the console : 
<quote>Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.</quote>

**Comment by Phr33d0m** [comment]
Report it to arcgames. Nothing to do with this script (which does no connections at all to the server afaik).
