### ISSUE TITLE
On Russian server does not consolidate AD

### ISSUE THREAD

**Issue by metacorez** [Phr33d0m/NW-Profession-Bot#213]
Good day!
On the Russian server did not consolidate the AD on the character of the banker. Perhaps the problem is that the names of the characters using Cyrillic letters. Orders without problems are set to 5 positions. Then no is a removal order and their consolidation on a character-the banker, only manually.

**Comment by noonereally** [comment]
I'm not sure. 
You tried to copy the name from one of the tabs ? Like "Refine Counters" it has all the character names, maybe copy pasting will solve it. 
I'll look into it if it's possible to make it a drop down the next time I'll change anything but it's probably loaded before the char list.
Is there any indication in the log ?  (ctrl+shift+j   and debug option should be enabled in the script)

**Comment by metacorez** [comment]
Good Day!
The names of the characters are short, and tried to copy it and enter it manually - no result.
Errors in log no. In the presence of 5 buy orders AD.
When switching to character banker in the log appears "Bank char not set or bank char, skipping posting." 
If it goes to the character who has, in the presence of AD - "Zen Max Listings Reached (5). Skipping ZAX Posting..".
As if no function is triggered cancelZaxOffer, "Canceling ZAX orders" present and and then nothing happens.

**Comment by metacorez** [comment]
if (parseInt(item.price) == ZenRate && item.ordertype == "Buy") { -- not Work
if (item.ordertype == "Buy") {   -- Work

**Comment by noonereally** [comment]
You used "Override account settings" for your banking char ?
If you did, try the last commit. It should be fixed.

Thanks for pointing where the bug is, it really helps.

**Comment by metacorez** [comment]
If you disable it "Override account settings" , everything works!
Thank you very much for your help!

**Comment by noonereally** [comment]
Update to the latest version, it will work with the override. I fixed it.

https://raw.githubusercontent.com/Phr33d0m/NW-Profession-Bot/master/main.js
