### ISSUE TITLE
Bot leave empty slots

### ISSUE THREAD

**Issue by IamFake** [Phr33d0m/NW-Profession-Bot#216]
Hi there.

Sometimes, when gateway is laggy, robot leaves slots empty, but sets a "next task" for this char to ~40 min.

version 4.8

**Comment by noonereally** [comment]
The old behavior fully ignored empty slots, and return to the char only when another slot finished, now you can set the time for the script to recheck an empty slot, it's the last option in "script  options" tab.
In case of severe lag, you can increase the time the script waits for the gateway to react, it's "Increase script delays by" option under same tab.
