### ISSUE TITLE
[Leadership -Request- ] Buying resource and hiring new mercenery t

### ISSUE THREAD

**Issue by ozgurturk** [Phr33d0m/NW-Profession-Bot#227]
Hi,

When there is an empyt slot for profesion task, could you make possible to produce hire new mercenary and higher rank workers ?

In addition to that, buying resources for leadership won't work. For "worn infantary armor-weapon" when there is a task requires these items.

**Comment by Phr33d0m** [comment]
Hi, both things are currently working without issues. For your first issue you're probably using a (new) custom profile which does not include training assets.

We'd need more info about this.

**Comment by ozgurturk** [comment]
Hi, I use RP Double Coffer ( stacked assets ). I did not add or change anything with this profile. How I can organize different profiles to train new workers and buy necessary resources for specific tasks ?

**Comment by Phr33d0m** [comment]
Oh, I think I see the issue. We don't have `Leadership_Tier1_2_Training` set above level 5  (nor the Guard one above level 22) of the profession. That might be the issue you're experiencing.

**Comment by noonereally** [comment]
Make sure you have the train assets checked in options.
If you want one slot to behave differently you will have to use the per slot allocation tab.

**Comment by Phr33d0m** [comment]
Closing as per #247
