### ISSUE TITLE
Extra Assets

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#23]
Selecting "Tools asset for  RAre task" not working properly.

Current selection works with "workers", but there is reported problems when selecting "Rare" task tools.

Buntas original selection part was report to working better.

**Comment by Phr33d0m** [comment]
Any easy way to reproduce this?

**Comment by RottenMind** [comment]
Bug with Extra assets, Confirmed.

Rare task used, "Leatherworking_Tier1_Leather_Helm_Special_1", lvl6.

I have 9x rank1 Leatherworker and 6x worn quality tools
1. Script loads selected task
2. It fills optional slots with workers!!!!
3. Script start second slot for same task, loads correctly
4. It fails use fill any extra tools!!!
5. script start task same time when it try fill tools.

## NOTE!!! Alchemy worked fine!!!!

**Comment by Phr33d0m** [comment]
There's no current logic that does what you want. 

The bot runs through the slots and just select random items that are allowed by that slot. For example, some Alchemy tasks only allow a Crucible, and the task you're having issues with allows all kind of optional assets so the bot just fills with the first available asset it finds (may it be a leatherworker or a tool).

This has been the logic since forever so I'm not sure if this worked 'better' with any previous version of it (e.g. Bunta's).

**Comment by RottenMind** [comment]
Only way replicate this Bug is select Profession what fails. Leatherworking is only reported and I tested current "asset selection" with Jewelcrafting/Alchemy/Leadership so my conclusion is bad coding in Gateway end and our end need do more testing... 

Switching back Buntas orig. selection untill this is solved, but I like implement some current build updates too. Need fork working additions and continue testing others...

**Comment by RottenMind** [comment]
Sorry, Alchemy select assets correctly, Leatherworking select assets wrong way,

Bug with Extra assets, Confirmed.

Rare task used, "Leatherworking_Tier1_Leather_Helm_Special_1", lvl6.

I have 9x rank1 Leatherworker and 6x worn quality tools
1. Script loads selected task
2. It fills optional slots with workers!!!!
3. Script start second slot for same task, loads correctly
4. It fails use fill any extra tools!!!
5. script start task same time when it try fill tools.

Again, 

Alchemy,

I have 7x Alchemy workers rank1 and 4x Epic quality tools + several worn quality
1. Script loads selected task
2. It fills optional slots with highest quality tools
3. task Start correctly

Second task cant be tested because my char. lack ingredients, but I think this shows something. So there is some kind bug.

**Comment by RottenMind** [comment]
Now I tested it again with same outcome,

Alchemy, correct assets use
Leadership, use Rare task slots workers.

You need just log in Gatewaytest and you see how it works and not-works.

I revert back Buntas original and lets see what it do, ;) .

**Comment by RottenMind** [comment]
Buntas original, Leatherworking
1. Script loads selected task
2. It fills first optional slots with worker and continues with tools
3. task Start correctly after selection

Buntas original, Alchemy, OK.

IDK, how they are worked before but Asset selection works different way per profession?

**Comment by RottenMind** [comment]
I mailed workers away,

I have 1x rank1 Leatherworker and 6x worn quality tools,

Buntas orig. select tools properly

Current model, selects nothing.

I cant test it with Purple tools, because I dont have them now.

**Comment by RottenMind** [comment]
Solved one issue,

var $assets = $("div.modal-item-list a").has("img[src_='_Resource_'],img[src_='_Assets_']");

needs addtion, img[src*='_Tools_']

---

var $assets = $("div.modal-item-list a").has("img[src_='_Resource_'],img[src_='_Assets_'],img[src*='_Tools_']");

---

Works perfectly, but need check if Gateway contains othe Bunny traps!

YES, code is done properly, just need look that all tools search strings are on place.

Was good lesson for thinking and searching... xD

**Comment by RottenMind** [comment]
Im not sure about this, but it seems that search just needed few extra strings and if I looked porper place, new line looks like below

---

var $assets = $("div.modal-item-list a").has("img[src_='_Resource_'],img[src_='_Assets_'],img[src_='_Tools_'],img[src_='_Tool_'],");

---

Leatherworking use  "_Tools_", Tailoring "_Tool_" so it should work, correct?

Purple and Blue asset names are not tested.

**Comment by RottenMind** [comment]
This "WAS" bug and it still behave unaccepted way.

**Comment by RottenMind** [comment]
I move this to issue what covers more.
