### ISSUE TITLE
Using per-slot allocation option stops rotation through chars on account

### ISSUE THREAD

**Issue by 3bagorion33** [Phr33d0m/NW-Profession-Bot#230]
Whell not finding solutions with the profile for crafting aqua vitae I decided to set tasks manually for each slot. As a result, the rotation of chars and timer for next task were stopped. I have 3 chars on acoount and use this option on 2nd only. When I turn it off all works as expected.

**Comment by noonereally** [comment]
Can you please paste the last lines of the log when it happens (replace char names with something before you do).

**Comment by 3bagorion33** [comment]
I have not understood how to use the logging. Where should I copy?

**Comment by Phr33d0m** [comment]
Closing as per #247
