### ISSUE TITLE
Issue with using epic assets.

### ISSUE THREAD

**Issue by NWHat** [Phr33d0m/NW-Profession-Bot#235]
Hi,

Problem I'm experiencing is getting the script to use my epic tools, including my gond.  I have optionals set to quality and the gond box checked, but every time the custom task comes up, in this case aqua fortis, it just uses the primary tool and doesn't add anything. 

It is a masterworks task so I wonder if the purple 'alembic' is causing a problem.

Thanks for any suggestions you might have

**Comment by noonereally** [comment]
Try changing the optional settings to speed and then back to quality, and uncheck the gond and check it again.

**Comment by NWHat** [comment]
Appreciate the tip but it didn't work.  

After I posted the message about not slotting epics, I decided to do a 'fresh' install of the script.  It worked the very first time, but after that, back to just starting the task and not filling in optional assets.

I even tried checking the 'fill optional assets' under the professions tab to see if it would solve the issue, even though it would auto fill all slots, but that didn't work either.

Quite the mystery.

**Comment by noonereally** [comment]
It should be checked. Do you have account setting override for that char ?
Does it fill them when you don't use the per-slot allocation ?

**Comment by NWHat** [comment]
No, I don't have the account override setting checked.  I've tried using the 'tasks' tab as well as the per slot tab to get it to fill the epics with no luck.

I have edited the 'default' script for that profession so it'll do the tasks I want, but it's selecting the right task so I don't see how that would have been the problem.

**Comment by noonereally** [comment]
Make sure "fill optional assets" is active. 
So far it works without issues both with per slot allocation and the regular tab, so I think it's a configuration issue.
To help further I'll need the log and the settings dump, you can get the settings by going to advanced tab and click dump settings, verify that the account and password are not there (there is a small bug that didn't remove those, I've fixed it here: https://github.com/noonereally/NW-Profession-Bot/blob/master/main.js  if you use that build, disable auto updates.)
You can use githubs gist (https://gist.github.com/), pastebin or something to link it.

The log is similar, enable debug in script settings, and press ctrl+shift+j to see the log, make sure when you copy it to remove any char names or account info. 
Unfortunately you will have to do this manually. I will only need the section when it sets the tasks to see what going on with the optionals.

You can also try again a non modified version, just set it, check "fill optional settings" in account settings, and set the fill optionals to "quality" for the profile you want for a char.

Also does it work on any profession at all ? Leadership ?

**Comment by killmantor** [comment]
I don't know if this was resolved or not. I had similiar issue (without Gond since i don't have it) I had Alchemy masterwork set to Quality (per-slot task) and it didn't use tools (it opened tool selection box though). When I have set it to purple it started using purple tools.

**Comment by Phr33d0m** [comment]
Closing as per #247
