### ISSUE TITLE
Exchange rate ZEN/AD graphs

### ISSUE THREAD

**Issue by 3bagorion33** [Phr33d0m/NW-Profession-Bot#237]
Is it possible to do? This would be useful for monitor the time of day цhen is profitable to buy or sell ZEN.

**Comment by Phr33d0m** [comment]
https://www.nwo-uncensored.com/phpBB3/app.php/nwountools/markettools
[Register in their website for full functionality].

Implementing this using their API is doable but beyond the scope of this project. Pull-reqs are welcomed any time though.
