### ISSUE TITLE
Resource tracker customization

### ISSUE THREAD

**Issue by ketacz** [Phr33d0m/NW-Profession-Bot#240]
Hello!

I would like to come back to the resource tracker feature.
It would be great to have and easy way to define which resources are visible there apart from those "hard coded" in the code.

I know it can be done by manually removing them all and creating a custom list but as it is now it's quite a hassle with a lot of clicking.

I tried finding these pre defined items in the code but no success.

Any help please?

Thanks!

**Comment by Phr33d0m** [comment]
Closing as per #247
