### ISSUE TITLE
Alchemy: how to change priority for tools?

### ISSUE THREAD

**Issue by 3bagorion33** [Phr33d0m/NW-Profession-Bot#241]
Hello again. I would use this script for crafting with T3 result. By default each cell is filled by crucuble. But mortar is cheaper and I want use it for filling.

**Comment by bruciaWillis** [comment]
Easy way: go in game and reorganize the tool/asset bag, put mortar in the top part, crucibile in the lower part.

Script gets 1st available/suitable starting from the top of the bag.

For example, if you put from top of bag mortar/mortar/crucible, that's the order they'll be picked for the optional tool slots (assuming they are all same quality).

**Comment by Phr33d0m** [comment]
Closing as per #247
