### ISSUE TITLE
Unrefreshed character issue

### ISSUE THREAD

**Issue by killmantor** [Phr33d0m/NW-Profession-Bot#242]
Hi,
First of all, thank you for this awesome tool its a lifesaver and for a casual player like me, it gets me by these days :). 

Recently on one of my newest char I have hit all 9 slots previously having 8. The bot however doesn't recognize that and I have it listed on that char at only 8. I have manualy trained L3 Leadership asset but in workers list on that char it shows only 5-L3 and 1-L1 (I think I had it like that when i first installed this tool). I have tried reinstalling the script but it still remembers the old values. Funny thing when it stated that this is a new installation it had to go every char to refresh aviable slots , workers and assets but on my last char it still shows old values (I have bought 2 mithral tongs recently on my main char and they are listed correctly) 

Its either a bug of some sort or I'm not understanding something here :D.

**Comment by killmantor** [comment]
Seems like it fixed itself. I noticed i didnt have a sword and armor for the task when I bought it, it started working after a time.

**Comment by Phr33d0m** [comment]
Closing as per #247
