### ISSUE TITLE
[enhancement] Idle

### ISSUE THREAD

**Issue by IamFake** [Phr33d0m/NW-Profession-Bot#246]
Gateway have 45 sec timeout (at least RU) and then disconnect user if him didnt take any action. This became a problem while all profession tasks are long-term (4h and 8h). I think bot must not perform "reconnect", but wait until timer for next task hits zero.

**Comment by IamFake** [comment]
Or may be this is just opera 37 and 39 bug\glitch. Firefox seems doesnt have 45 sec idle timeout...

**Comment by Phr33d0m** [comment]
Closing as per #247
