### ISSUE TITLE
Tabbed Settings

### ISSUE THREAD

**Issue by David3412** [Phr33d0m/NW-Profession-Bot#33]
As the number of options in the settings menu continues to grow, I would suggest adding the enhancement of a tabbed settings menu. Rather then displaying all of the settings options on a single page (which keeps getting bigger and bigger) each part of the settings menu should be split up into separate tabs.

As a bonus, this would make the script more modular so that anyone working on a new enhancement with a new set of settings can simply add a new tab.

I can work on this though it may take a while as I do not have much free time.

**Comment by Phr33d0m** [comment]
Hi @David3412, @mac-nw is already working on that (not sure what has been his progress though) - you can check it out at the [JqueryUI-Testing branch](/Phr33d0m/NW-Profession-Bot/tree/JqueryUI-Testing).

**Comment by David3412** [comment]
Ok, thanks for telling me.

**Comment by mac-nw** [comment]
Once this version is tested and stable we can start working more on the UI

**Comment by Phr33d0m** [comment]
Please submit any UI suggestions and improvements on issue #40.
