### ISSUE TITLE
Undefined 'name' when reducing the number of characters

### ISSUE THREAD

**Issue by Phr33d0m** [Phr33d0m/NW-Profession-Bot#36]
If you have 3 characters set up already but decide to reduce the characters to 2 [this line](https://github.com/Phr33d0m/NW-Profession-Bot/blob/0513d701a23d609508f1a7a778349f852c733204/main.js#L2149)
`for (var i = 0; i < (charSettings.length / settings["charcount"]); i++) {`
Gives an: `Uncaught TypeError: Cannot read property 'name' of undefined`

Expected behaviour would be to erase any characters that existed after charcount's number.

**Comment by RottenMind** [comment]
I can call this as "Feature", done so many times reinstalls and advised users do same.

When testing with 99x characters, it will be nice if I can just "add & remove char.count", but its not big issue because normally you just add characters... well, good anyway if character count change wipes settings so script dont try catch "ghosts".

**Comment by RottenMind** [comment]
With GM_deleteValue it can be done... tested "Settingswipe" and it worked... deleting GM_values  needs just filter.

Problem is that GM_getValues and GM_listValues(charSettings) gives same list, check link to get better idea, maybe solution is there allready.

https://gist.github.com/RottenMind/1acaafb64bcf889f8a81

**Comment by mac-nw** [comment]
Would it not be best to move the settingswipe code at the bottom to remove all saved settings and then resave them?

**Comment by mac-nw** [comment]
I uploaded a fix, tested it with one character removed and then ran through a full cycle until the last character. Rotten please confirm testing :)

**Comment by RottenMind** [comment]
...will do, will do, xD

BTW, Русский шлюз работает с моим модом, bad bad google translate...

Edit, if you uploaded FIX, who ate it?

**Comment by mac-nw** [comment]
Github gobbled it up and digested with into the main branch :)

**Comment by RottenMind** [comment]
...Git -junkies work... all your FIX belongs to them...

FIX works, "Wipesetting" can be added after UI is updated. It will be needed after setting pages are diveded "sub menus", but current UI needs it NOT because its really easy "click" clear.

**Comment by mac-nw** [comment]
With the pull request to only use defaulttasklist the save/clear tasks is removed (not needed).

**Comment by Phr33d0m** [comment]
So is this fixed now? :p

@mac-nw pro-tip: if you add 'Fix issue #36' to the commit, github will auto-close the issue.

**Comment by mac-nw** [comment]
Ah, i thought there is some way to do this automatically. I'll try to remember it in future :)
