### ISSUE TITLE
Sell Crafting resources

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#41]
...no gold but Infinite Gathering and Lazy clicker, let script do some job,,,

I started testing with, 
- sell xxx resource from "Ресурсы ремесла"(I think it is Crafting resource bag) if gold is less than X
  (easy mod with current script items!)

This is just test if can "Automate" gold gain before Leadership reach level where it brings adequate amount gold for account use. This can help lot those who has multiple accounts and no resources or time to transfer resources/gold between account.

This needs check for "Exclude" -filter, because some Rare -resources should not enter accidentally in sale list and it might need own TAB in UI, but time we have.

**Comment by RottenMind** [comment]
I use this build on "gather only" on LIVE account, really good cleaner,
- need code check, my abilities lacks better solution
- added "tradebag"
- added "RAW" sell filter
- added "Exclusion" filter

https://github.com/RottenMind/NW-Profession-Bot/compare/master...RottenMind-trade/sell-1

Exclusion filter add,
- "Crafting_Asset|Craftsman|Aqua|Vitriol|Residuum|Shard|Crystal|District_Map|Bill_Of_Sale|Refugee"

, prevents most unpleasant sales when sale filter is
- ^Crafting_Resource_.*

It needs more controls, what means more UI options and whole section might need "Advanced filter"  TAB where you can enable/disable exclusions/Quality -filters so you can sell what ever you want.

...so it while new UI is  getting ready, I collect some stuff what fills it up, ;).

**Comment by mac-nw** [comment]
If they are capable of reaching the required level to start professions (9 or 10?) then they should have the time to get some gold from a shared bank or guild bank...But still this option can be nice for keeping resources bag clean to the point where remaining resources are either worth selling in larger quantity or ones being used in professions. For sure this list might need to be custom at-least to the level where u can select which professions to sell resources for rank 1/2/3 and separate select for profession and purchasable resource.

**Comment by mac-nw** [comment]
A good start here would be to put regular expressions together for each profession and rank there of.

**Comment by RottenMind** [comment]
Yes, adding more customization is just "filtering", but code itself needs look up so its not contain unneeded portions or is done stupid way.

Current "Exclusion" system is really overkill to prevent unwanted sale actions, but each profession crafting item can be added individually if  UI permit it... or do what ever we like to do, this is just testing and it works.

**Comment by Phr33d0m** [comment]
I agree with @mac-nw, and as I pretty much like the idea of getting gold from thin air I'm not really happy with this approach. If you have a in-game bot farming foundries for you then just sell the stuff you don't need afterwards.

Currently the bot has the ability to sell anything that _actually drops from professions_ (i.e. the chests). I wouldn't like to see the bot doing anything out of profession-related stuff - and selling a random list of items from the professions bag isn't helpful at all (even if it gets you some miserable gold) because I might **not** want to sell anything until (as @mac-nw said) have a large quantity of it and want to sell it for AD at the AH.

**Comment by mac-nw** [comment]
I think this this should be a low priority nice to have we can look at in future

**Comment by RottenMind** [comment]
Well, you get it all wrong. This is just one addition over others, it is not TOP priority, it is not ready, it is way get gold for accounts what you cant handle.

Botting is limited because most computer can run 2 - 4 bot simultaneously so Botting has nothing to do with this.(Bots has also sell option, but for Free Astral Bot good "junk" filter is must, and I know how it work)

Those who have + 8 accounts or +16 characters, want just easy way get rid all trash and new players want keep all so good filters are needed and I already mentioned that this option needs good choices so it can be used good way.

...and you can keep all stuff you need, dont "enable" option you dont like.

**Comment by mac-nw** [comment]
But we want people with 8 accounts to do some work at-least.. Just joking.. If you want to start putting those lists together we can get to it at some point.

**Comment by RottenMind** [comment]
I don expect ... others get involved, but as you know I dont push away either... xD

NW game play is not so "fun" anymore, but Bot is still fun and making "Passive leveling" for it, is what this "sell gathered" items do and it feels fun to look.

Allmost all professions needs,
- residuum 

, for effective leveling. Alchemy is exception.

All professions needs, Gold for,
- refining

, but can level up with "Gathering, Alchemy is exception.

So we have one exception what has few caveats but all other goodies?
- no needs for Residuum (script cant auto AH)
- needs gold (script can "auto sell")

, so I will setup it for Alchemy, fun to see how leveling works, I think it will be 99% standalone, and Alchemy also make AD´s from air... sell gathering, get gold, make vitroils, sell AH, get "Green worker", hmmm, did not think this far before, I need do some rethinking...

...but some other professions can do level1 -jobs with out,
- Residuum

, but not with out,
- gold

, those exceptions are easy to add "no Residuum" tasklist, ;), but this needs Gold and gold can be done from "Air"... it is not effective method to level, but it is more effective than gathering only and it will not consume your time after you set i up.

**Comment by RottenMind** [comment]
Well, it seems that with "sell gathered" + extra tasklist, I can left script "infinite" gather-sell-refine loop and get items what can sell in AH better than raw materials and all the time profession moves forward "slowly".

Adding extra tasklist just feels stupid, but its only way prevent other Profession refining task when you need just Gathered materials from them.

...but still, user must do correct choices and look once or more per week refined items to AH.

**Comment by RottenMind** [comment]
Alchemy level up, only user interaction needed is setup new slots.

Other profession level up, only tasklist check and its ready to go.(need look no residuum + other task)

If user transfer gold, no T1 gathered items are sold if copper is more than _set_ threshold, current is 4000.

## _"If gold can be made from Air... let's do it!!!"_

**Comment by dlebedynskyi** [comment]
Alchemy has issue with Auto Vendor lesser potions #. It makes a potion and then sells it. So can not run experiments task

**Comment by RottenMind** [comment]
Alchemy + Auto Vendoring is not script issue, user must just select proper options.

Vendoring gathered items will be added Greasyfork -build when some one ask it.
