### ISSUE TITLE
Selecting Assets, infinite loop

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#46]
Selecting assets if have no assets can cause "Infinite loop". This loop comes back after page reload.

Tested with,
- Alchemy

Continuing testing if it happens allways same way. Simple reason why this is not detected before this way is that we dont have "ZERO" accounts for testing.

Im testing RU GAteway stuff, sell gathered and there you can see what happens when you have "nothing".

**Comment by GlowingCrystallineEntity** [comment]
This looks like one of the things I fixed.  Please check it out.

**Comment by RottenMind** [comment]
Yup, this seems to be done. THX

**Comment by Phr33d0m** [comment]
Please don't close issues until the changes have been actually commited.

**Comment by Phr33d0m** [comment]
Fix already commited some time ago so closing.
