### ISSUE TITLE
Better concept for "list"

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#48]
Current filtering list system working well, but it is hardly "human readable", RegEx is good tool but even with it list became long,

---

```
    var _excludeItems = /(^Crafting_Resource_(Charcoal|Rocksalt|Spool_Thread|Porridge|Solvent|Brimstone|Coal|Moonseasalt|Quicksilver|Spool_Threadsilk)$|Crafting_Asset|Craftsman|Aqua|Vitriol|Residuum|Shard|Crystal|District_Map|Local_Map|Bill_Of_Sale|Refugee|Gemfood|Gem_Upgrade_Resource|Artifact|Hoard|Coffer|Fuse|Ward|Preservation|Armor_Enhancement|Weapon_Enhancement|T[5-9]_Enchantment|T[5-9]_Runestones|T10_Enchantment|T10_Runestones|4c_Personal|Item_Potion_Companion_Xp|Gateway_Rewardpack|Consumable_Id_Scroll|Dungeon_Delve_Key)/; // edited by RottenMind 17.01.2015
```

---

Can you make it work like "tasklist" with categories and if using different method is there bigger risk that list can fail?

I can do "convert" + testing. Those lists grows bigger and they are easier maintain if they locate one position on script(if possible).

...and if items names are moved to list what can be used as variable, then once work is done it can be reused easily around script or edited/checked if needed.

Quality filter is exception(contains "bound" +"item quality"), it should stay "hidden" because it prevents most disasters after bad "filter+sell_list".

ps. checked, making list with categories can be really extensive job, but when list fails on some point its then easy locate failures.

**Comment by Phr33d0m** [comment]
I hardy see this as an improvement. It doesn't have to be "human readable", we're not human - we're programmers and that my friend is "programmer readable" :-P ... but yeah, we could make it an array of things (and as you said per category(no idea why the need of this either)) and just run through the array until we find the thing...

Hardly to none an improvement and long lines aren't an issue if it improves the script's performance (`regex` vs. `for()`)

On a side note: I **really really really** try to understand you, and sometimes I re-read your stuff 2-3 times to get the idea - if I got it wrong, sry about that.

Edit: if we wanted to improve the code to get it to at least "programmer readable" (there are some 'eeeww' parts of the code now) we'd need quite a refactoring, and this isn't where we'd start from IMHO. For example: remove any unnecessary commented out code, move important stuff to global variables (like `_excludeItems`) to the top, re-order the functions in some logical way, optimize some stuff (`processChar()` and `switchChar()` have a lot of similar code IIRC) - and all this (and more) **after** of course fixing all the known issues :-).

**Comment by RottenMind** [comment]
Yes, I have difficulties with english and it is sometimes really hard to write it.

...and Im sorry that I can support users better than programmers so what I asked here was for users not for programmers.

If you cant understand what Im writing how you can deny what Im asking, xD. 

(off topic and hopefully hard to read)
If strip all comments from script it will became harder to maintain for new people and you know that. Script is abandoned allready twice by Mustex and Bunta. I took it over because I liked idea keep it alive, Github I started because I wanted script code to be more redundant so if I quit maintain Greasyfork page or script get some fatal errors, then any one can try find code from Github/Greasyfork.

**Comment by Phr33d0m** [comment]
I denied based on what I could understand. From a developer's POV (Point of View) - the user has no job looking at the code at all, if he does that it's because he knows what he's doing - and if he knows what he's doing he's a programmer :-).

I never said removing the comments, moreover comments are a **must, always!!** both for us that develop it and for new contributors that might appear. I did say removing the commented out code that's of no use because it's outdated.

In the same line of thought, like I've already said in the past, things like `// edited by X` are not necessary anymore - Github shows who edited what line and when :-), but that's not that important.

**Comment by RottenMind** [comment]
OK, check filters, something is missing and something is wrong, Greasyfork build will be updated for users and maybe you grab updates later.

(off topic)
If you denied user POV and ability alter some code... well, then I see.

Script came from Userscript.org and you denied sources POV... I dont mind if some one perfect code so just do it, nothing changes, ;).

BTW, as you know Im not programmer at all, I just do this for fun, because I like it and I can.

**Comment by RottenMind** [comment]
This is no longer issue, it continues if we like do changes in greasyfork build.
