### ISSUE TITLE
Multi Url support

### ISSUE THREAD

**Issue by RottenMind** [Phr33d0m/NW-Profession-Bot#5]
I added script to support multi Url,
- Gateway
- RU gateway
- gatewaytest

It just detect start page and switch "current_Gateway" variable on to match, exist four places on script.

Tested it with Gatewaytest, but cant test it on RU Gateway.

I also did Junk -filter what sells profession stuff what comes when leveling PRofessions, last upgrades items what cant be upgraded anymore. 

It is "static" list  extracted from current "Profession tasklist" so it cant sell items what are crafted out off list, also it is difficult test all items on list.

**Comment by Phr33d0m** [comment]
Was this supposed to be a pull-request? :-)

**Comment by RottenMind** [comment]
Im not sure if its worth to do and if it cause more problems than solve...
