### ISSUE TITLE
Customizable asset upgrading per profession.

### ISSUE THREAD

**Issue by TheBeerBaron** [Phr33d0m/NW-Profession-Bot#54]
Would it be possible to refine the "upgrade assets" button and have a box next to each profession for each character (and thus possibly removing the option from the top section altogether)

This way, I can choose then for any single character if I wish to upgrade the "leadership" assets for example - while leaving my 4 blue assets doing Artificing as I do not wish those upgraded.

Maybe a "Upgrade Assets?" header with a "yes/no" dropdown for each profession for each character?

I know I could just edit the script and remove the update parts for the professions I don't want - but I think this would make a nice little addition to the script?

**Comment by BigRedBrent** [comment]
I thought that only upgraded the white quality workers?

**Comment by TheBeerBaron** [comment]
I have pushed a script with my above changes coded in - if someone can check and test that would be great.

**Comment by dlebedynskyi** [comment]
I added Upgrade assets to purple for Mailsmithing profiles I added. Probably we can do same for other profession. 
https://github.com/Phr33d0m/NW-Profession-Bot/pull/57

**Comment by TheBeerBaron** [comment]
Looking at the profiles in more depth I should have put the "U" profile AFTER the main profile.... that way - only in the situation where no asset is available for any of the regular profile tasks, it will switch into the upgrade "U" profile and either train or upgrade the current profession workers.  These could be included into a new dataset which just contains the worker upgrade paths (white,green,blue and purple) which would then keep it separate from the regular profiles which should make them less messy too.  Thoughts?

**Comment by Phr33d0m** [comment]
From what I can currently see we don't use any worker upgrading above rank 3 (common/white asset). Also, with custom professions one can make whatever the needs so closing this for now. If it's still a thing open a new issue or send a pull-req this way ^.
