### ISSUE TITLE
Alchemy and "Experimentation"

### ISSUE THREAD

**Issue by TheBeerBaron** [Phr33d0m/NW-Profession-Bot#56]
When you have more than 1 slot allocated for alchemy and "research" has been assigned to a slot, the script will hang continuously attempting to fill the remaining alchemy slots with the same research task - which, as it can only be started once - will stop the script from character switching or completing other tasks until the experimentation completes

**Comment by dlebedynskyi** [comment]
This is due to Alchemy_Tier1_Refine_Special is used instead of Alchemy_Tier1_Refine_Basic
You can update your script locally. I have fix in my commits so should here soon after I finish planned changes

**Comment by Phr33d0m** [comment]
The fix for this has been merged. I'll release a small patch version in a moment.
