### ISSUE TITLE
New TaskList Concept

### ISSUE THREAD

**Issue by WloBeb** [Phr33d0m/NW-Profession-Bot#68]
I'm thinking about a new way of tasklists definition. And please do not reject it without reflection.
My idea is this: after definition - for each level connect with the lists of lower levels (in fact, doing that recursively from the bottom, with list of level-1). Alternatively, with the exception of repetitive tasks.

cons of this solution:
- at beginning at first glance, the tasklists are maybe more difficult to understand
- I'm not sure how about addProfileToDefined() function

advantages of this solution:
- no need to add safety tasks ("gather basic") at end for each level
- less possibility of error in the definition of the list
- no need to repeat the same list for each level (if nothing changes)
- much shorter tasklists
- existing definitions should work as before
- if ever happen increase in level of profession in NWO all lists can be enlarged by increasing the counter in a loop

And all that we can do with one additional function before:
  // Profession priority list by order
    var tasklist = [  ....

An example of definition after such changes (functionally equivalent to the current "default" list):
level: {
                0: ["Weaponsmithing_Tier0_Intro"],
                1: ["Weaponsmithing_Tier1_Dagger_1", "Weaponsmithing_Tier1_Gather_Basic"],
                4: ["Weaponsmithing_Tier1_Dagger_2"],
                7: ["Weaponsmithing_Tier2_Dagger_3"],
                14: ["Weaponsmithing_Tier3_Dagger_4"],
                20: ["Weaponsmithing_Tier3_Dagger_Set_2", "Weaponsmithing_Tier2_Dagger_3],
                21: ["Weaponsmithing_Tier4_Gather_Basic"],
                25: ["Weaponsmithing_Tier4_Refine_Basic", "Weaponsmithing_Tier4_Gather_Basic"],
        }

and newly added "Gond Task" list should look like (without addProfileToDefined()):
level: {
                0: ["Weaponsmithing_Tier0_Intro"],
                1: ["Weaponsmithing_Tier1_Gather_Basic"],
                6: ["Weaponsmithing_Tier1_Event_Gond"],
         }

Regarding addProfileToDefined() function there are 2 possibilitis:
1. Expand orginal tasklist before concatenation with additional task.
2. Additional tasklist at level eg. 15 removes all original list from levels >=15.

**Comment by noonereally** [comment]
I wanted to suggest a solution for the gathering (the now closed), by just searching for lower task. with no recursion, but finding the first non null level at a given profile that is lower than the given level.

It shouldn't affect anything at all, except allowing 'missing' lines.

Something in the sort of: (at line 2200)
http://pastebin.com/VtR78yL4

This way the gathering tasks can be just 4 lines, at the appropriate levels.

**Comment by WloBeb** [comment]
This concept is similar but much easier, witout any changes in code.
Only after all definedTask definition or even after tasklist creation:

<pre>
for every profession {
    for every profile {
        for lvl = 2 to 25 {
            if tasklist[profession][profile][lvl] is undefined {
                 tasklist[professio][profile][lvl] = tasklist[profession][profile][lvl <b>-1</b>]
            } else {
                tasklist[professio][profile][lvl] <b>+</b>= tasklist[profession][profile][lvl <b>-1</b>]
            }
        }
    } 
}</pre>

But I'm not sure, if this idea gain acceptance, so I do not know if it make sense to code.

**Comment by WloBeb** [comment]
BTW "Mass Gathening" profile is more needed than yesterday because <b>Bags Now Bind On Equip</b> (to Character :( )

**Comment by Phr33d0m** [comment]
@WloBeb I like the idea.

**Comment by dlebedynskyi** [comment]
Yeah I came to this idea myself. will work on function as soon as I have time.

**Comment by noonereally** [comment]
I agree that something like that should be done, but not sure if it is better to be done in the task selection like:
https://github.com/noonereally/NW-Profession-Bot/commit/81aecb204134772dba014b0cd6a793f4f28ae649

Or reformat the tasklist like @WloBeb suggestion.
i'm not 100% sure about:

```
else {
+                        profile.level[i] = profile.level[i].concat(profile.level[i-1]);
+                    }
```

I'm not sure it's needed
This way I feel that it will make tasklist not easy to debug and behave in a way people do not expect at a glance.
But i can also see how it can make fallbacks easier for the tasks.

**Comment by dlebedynskyi** [comment]
https://github.com/Phr33d0m/NW-Profession-Bot/pull/74
Pull ready. Cleaned up a bit. function is uber. Plunker to play https://jsfiddle.net/63f7mpf6/11/

I did recursive Configurable. It is easier to maintain and understand list this way rather then noonereally@81aecb2

**Comment by WloBeb** [comment]
@noonereally say: "This way I feel that it will make tasklist not easy to debug and behave in a way people do not expect at a glance."
I think, it's just a matter of habit. 
Please note that I left the old profiles unchanged.
