### ISSUE TITLE
Names of 20>25 gather professions

### ISSUE THREAD

**Issue by TheBeerBaron** [Phr33d0m/NW-Profession-Bot#75]
Can you alter the names of the profile to 21>25 gather - since if you are level 20 and try to use Tailoring for example - there is nothing defined for 20 and the script will hang.  The mass task becomes available at 21 and therefore should use the default profile until you hit 21.

**Comment by WloBeb** [comment]
Whole way of defining tasklist is currently in the process of change and likely to be changed soon (maybe over the weekend).
And profiles "21>25 gather" most likely will be replaced by profiles "mass refining".

**Comment by Phr33d0m** [comment]
Indeed there are some 20>25 profiles that start at 21. Once we settle down some of the things going on we'll change it.
