### ISSUE TITLE
alchemy experiments blocks other tasks

### ISSUE THREAD

**Issue by dlebedynskyi** [Phr33d0m/NW-Profession-Bot#83]
Seems that alchemy experimentation locks tasks execution leading to constant loop for another slot. 
While task is running in one slot all other alchemy slots hang in loop. This blocks all task list for all chart. 

Looking at it now. Seems that adding regia task unlocks loop. Now in testing.

**Comment by Phr33d0m** [comment]
Thanks for the fix.
