### ISSUE TITLE
Professions hang up. Found real error

### ISSUE THREAD

**Issue by dlebedynskyi** [Phr33d0m/NW-Profession-Bot#87]
ok we have a problem at following lines 

``` javascript
  console.log('Selecting profile: ' + profiles[0].profileName);
        var list = profiles[0].level[level];
        if(list.length <= i) {
            console.log("Nothing Found");
            switchChar();
            return false;
        }
```

at lvl 25 

```

i = 5
list
["Leatherworking_Tier4_Leather_Shirt_Special_2_Set2", "Leatherworking_Tier4_Leather_Shirt_Special_2", "Leatherworking_Tier4_Leather_Pants_Special_2_Set2", "Leatherworking_Tier4_Leather_Pants_Special_2", "Leatherworking_Tier4_Leather_Shirt2_Set2"]
```

This was introduced by @Phr33d0m in  https://github.com/noonereally/NW-Profession-Bot/commit/724336c153338e789a259b6655d974923d236e2f

Anyone have idea why? 
Looks like it can not find resources for task and does not fall back to next one. we also have weird loop going there that do not allow to switch char

**Comment by Phr33d0m** [comment]
That "manual merge" was a nightmare, I might have screwed something up so feel free to send a pull-req if you got a fix. Although I believe our issue dates way before that commit you're referencing.

**Comment by WloBeb** [comment]
@dlebedynskyi 
I have only 1 question: how many slots you assign for Leatherworking? More than 3?
If yes, its only tasklist bug - first 4 tasks are "rare". Only fifth task is common. But as I remember, you could start only 3 of them (like all Leathership tasks).
If script calls function createNextTask(prof, i) with i=5, this means that couldn't <s>start</s> find tasks 0-4 ie. all on your list.

**Comment by dlebedynskyi** [comment]
@Phr33d0m  I reverted that. It was in separate brunch. I just references defect. This is not a pull request.

@WloBeb   i was not issue on leadership actually.  Im running 1 slot for "craft  Elemental Tunic". other slots - 8 on that char I think - are running leadership/alchemy.

 Trick was in that i did not have elemental aggregate for that task as required. and script is looping at lines above.  i is 5 so it tries to switch char but comebacks to this function call. 
I tried debugging this - hell really - and it seems that we run that method in multiple threads  due to setTimeout calls for it. 
I tried to reload page - effect is same - goes into loop. 
I all requirements are met all is good.

**Comment by WloBeb** [comment]
So, as I say: it's tasklist bug. You have list with tasks, each of which could be impossible to do for this profession. Four first are rare and may not be available, fifth of them is dependent on resource from another profession. Just add any refine or gather task at the end of tasklist and no more hangs.

**Comment by dlebedynskyi** [comment]
yeah you actually might be right on this one. I thought we had refine there. fixing.
