### ISSUE TITLE
Updated #Vendor options wishlist requests

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#90]
Hello.

I have few ideas/questions about #Vendor options:
1. Compact these options to have less option line (readeability)
   - Auto Vendor Enchants & Runes 1 - 3 (end game users)
   - Auto Vendor Potions Lv1 - Lv45 (end game users)
   
   This will save 7 options lines.
## Vendor: Unidentified green items
- Sell ALL unidentified green items (our class or not + even Lv60)
- Option to maintain Lv60+ unidentified green items
- Option to maintain Higher Lv items (if we are Lv30 KEEP Lv30+ items)
## Vendor: Unidentified red items

https://github.com/Phr33d0m/NW-Profession-Bot/issues/94
- Sell ALL unidentified red items
- Option to maintain Lv60+ unidentified red items
## Vendor: Clean up some english syntax:

Vendor/Maintain Prof Crafted LevelUp Items
to
Do not auto sell Crafted LevelUp Items 
## Vendor: Treasure items: 59/81 modelnames  22 are missing

https://github.com/Phr33d0m/NW-Profession-Bot/issues/90#issuecomment-102370247
http://pastebin.com/ndqSkKNg
## Vendor: Clean up duplicate items
- Sell ALL duplicate gear items
- KEEP 2 items for ring gear

Thank you so much.

**Comment by Phr33d0m** [comment]
1. We're not afraid of having lots of options, that makes the bot do exactly what you want (some people want to sell only rank 1 & 2) so this is a no.
2. We already sell any unidentified green junk if you check the option "Autovendor Junk".
3. Sure.
4. We already do that with "Autovendor Junk" although we have to manually add the names of the items for sale (in order not to accidentally your entire inventory). So if we missed any junk items just open an issue with the names or (even better) send a pull-req.

**Comment by GeneralSheppard** [comment]
4. Sure I will try to help you with that.
Do you have a junk items list that are already in ?

**Comment by noonereally** [comment]
You can find the sell regular expressions  at the bottom, for now it's around line 4870-4900

Specifically junk is:

```
        if(settings["autovendor_junk"]) {
            _vendorItems[_vendorItems.length] = {
                pattern: /^Item_Snowworks_/,
                limit: 0
            }; // Winter Festival fireworks small & large
            _vendorItems[_vendorItems.length] = {
                pattern: /^Item_Skylantern/,
                limit: 0
            }; // Winter Festival skylantern
            _vendorItems[_vendorItems.length] = {
                pattern: /^Item_Partypopper/,
                limit: 0
            }; // Party Poppers
            _vendorItems[_vendorItems.length] = {
                pattern: /^Item_Fireworks/,
                limit: 0
            }; // Fireworks
            _vendorItems[_vendorItems.length] = {
                pattern: /^Object_Plate_/,
                limit: 0
            };
            _vendorItems[_vendorItems.length] = {
                pattern: /^Object_Decoration_/,
                limit: 0
            };
            _vendorItems[_vendorItems.length] = {
                pattern: /_Green_T[1-5]_Unid$/,
                limit: 0
            }; // Unidentified Green Gear
        }
```

**Comment by GeneralSheppard** [comment]
These items make Auto-vendor button not working, they are not sold.
- Delicate Dragon Brooch, Teasure, Jewelry
- Jeweled Bronze Harp, Teasure, Trinket

**Comment by Phr33d0m** [comment]
We'd need the actual datamodel names of those items.

**Comment by GeneralSheppard** [comment]
If you got a guide to have those datamodel names I'll go ahead to hunt anything who are not sold.

Best regards,

**Comment by WloBeb** [comment]
Install <a href=https://greasyfork.org/en/scripts/8506-nw-inventory-names/code>this script</a> and try to find crappy item in user bags (open <s>log</s> console in chrome/chromium with Ctrl+Shift+i)

**Comment by GeneralSheppard** [comment]
Thank you so much I will try to bring my guild mates to help me gather un-sold items for ya.
How look like the datamodel names?
Can you give me an example of where I must look into ?

**Comment by WloBeb** [comment]
You should:
1. Install this script
2. open console with Ctrl+Shift+i
3. login to gateway and select any character
4. Click button with yellow background (on top of the page)
Then you can see in console datamodel names of your items.
After line "   . Content of user bags" you have, ..... surprise ..... names of all your items :D

**Comment by GeneralSheppard** [comment]
I got these error:

GET http://gateway.playneverwinter.com/news?game=nw&lang=en 500 (Internal Server Error)
Uncaught TypeError: Cannot read property 'dataModel' of undefined

I have the yellow button 'Don't click me! Okay, login first and then click..."
I do the login, click on it, then don't see it anymore
Tampermonkey do not have the script activated even if I activate it.

I don't have this console it looks like all the web developpement console that google chrome have.

**Comment by WloBeb** [comment]
Do you select any character?
To be sure, go to the tab 'inventory' and then click this button.

**Comment by GeneralSheppard** [comment]
I choose my character and go to Inventory, then click on the item I want to look and nothing.
I do not even have the yellow button.

**Comment by WloBeb** [comment]
Questions: 
1. What browser do you use?
2. Did you install Tampermonkey
3. Did you install "NW - inventory names" script?
4. Is "NW - inventory names" script active on gateway page?

**Comment by GeneralSheppard** [comment]
1. Chrome Version 42.0.2311.152 m (latest version)
2. Yes latest version v3.10.109
3. Yes latest version v0.0.1.2015051402 update url: 
https://greasyfork.org/scripts/8506-nw-inventory-names/code/NW%20-%20inventory%20names.user.js

When I go to https://gateway.playneverwinter.com/ I have the yellow bar saying '
"Don't click me! Okay, login first and then click..."
Looks like NW - inventory names script is active as I can see it.

So I follow... login first, then click.
Choose a character, go to Inventory
There I do not see any yellow things at all aroud the Inventory page; and CTRL+SHIFT+I give me this.

http://image.noelshack.com/fichiers/2015/20/1431645601-nouvelle-image-bitmap-2.png

**Comment by noonereally** [comment]
Try first login in, choosing a character, go into inventory and **only then** clicking the script thing.

**Comment by GeneralSheppard** [comment]
Fact is that I do not have the script thing (yellow bar) after I login and I do not have it in Inventory page as well. As you can see on the screenshoot, my tampermonkey has no activated script when I am on Inventory page (even if I am sure it's activated).

**Comment by noonereally** [comment]
hmm you are right and i checked now, apparently the gateway uses HTTPS only to login but not after that.

Add at the beginning of the script 

```
// @include     http://gateway.playneverwinter.com/*
```

So the beginning  block will look like this:

```
// ==UserScript==
// @name        NW - inventory names
// @description Prints NeverWinterOnline items in inventory (including content of user bags!)
// @include     http://gatewaytest.playneverwinter.com/*
// @include     https://gateway.playneverwinter.com/*
// @include     http://gateway.playneverwinter.com/*
// @grant       GM_addStyle
// @version 0.0.1.2015051402
// @namespace https://greasyfork.org/users/8151
// ==/UserScript==
```

**Comment by GeneralSheppard** [comment]
Thank you.
Okay I do have now the yellow bar on the main Inventory page.
And guess what it worked.

For Oathbound Paladin (my class) :
Head_Guardian_Green_War_T03_L27: x1
Head_Guardian_V2_White_L32_Wpow_T3: x1

Got 5 red items:
Body_Greatweapon_V2_White_L33_Wlif_T3: x1
Body_Scourge_V2_White_L33_Wpow_T3: x1
Secondary_Scourge_V2_White_L33_Wpow_T3: x1
Feet_Scourge_V2_Blue_T3_Unid: x1      -unidentified
Feet_Controller_V2_Green_T3_Unid: x1 - unidentified

Looks like there are no red word at all exept maybe rarity (white, green, blue, purple).
Hope it will help

**Comment by WloBeb** [comment]
Sorry, as I remember, I wrote this helper script, when gateway has big problem with certificate, so I cann't use https.....

**Comment by GeneralSheppard** [comment]
Okay I am able to provide 59/81 treasure junk modelnames where only 11 was deleted by the script; 22 are missing still investigate

Here is the list:  updated 16/05/2015 +8 modelnames
http://pastebin.com/raw.php?i=ndqSkKNg

**Comment by noonereally** [comment]
BTW, the exclusion filter need to be updated, enchants go up to 12 and there are other valuables like shards.

**Comment by GeneralSheppard** [comment]
Updated previous pastebin linkwith 8 more treasure items modelname; 22 are currently missing
http://pastebin.com/ndqSkKNg

**Comment by Phr33d0m** [comment]
@GeneralSheppard please don't use pastebin.com or don't set an expire time. Trying to look through this issue now seems useless as all your links have expired.

**Comment by Phr33d0m** [comment]
Closing as per #247
