### ISSUE TITLE
Any chance to have international language ?

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#91]
Hello.

Would it be possible to have more language options such as French (as I am french) it would be awesome.

Thanks.

**Comment by Phr33d0m** [comment]
Not at the moment. I think we discussed this some months ago but it has never been a priority.

**Comment by GeneralSheppard** [comment]
Looking into the source code I was able to see:
var settingnames = [{
            name: 'paused',
            title: 'Pause Script',
            def: false,
            type: 'checkbox',
            pane: 'main',
            tooltip: 'Disable All Automation'

If I translate here (title and tooltip) and save it in French, will it be in French?

**Comment by WloBeb** [comment]
@GeneralSheppard  Yes, you can translate ('title'  & 'tooltip' only), but how do you want to upgrade script in the future?

**Comment by GeneralSheppard** [comment]
I have no idea Sir. Sometimes I do appreciate to read French and not English but it's not a problem for me, it's my guild mates; they're bad in english and I want that my guild mates follow that awesome script.

Do you often release a new patch ? Like once a week or less ?

**Comment by WloBeb** [comment]
Look at <a href=https://github.com/Phr33d0m/NW-Profession-Bot/commits/master>this</a> :D. 
I know, these are mostly minor changes...

**Comment by GeneralSheppard** [comment]
Wow okay every 1 or 3 days amazing.
I'll found a way or explain them few minutes about how to use it.
And I gonna wait net days/weeks that it's implemented.

Thank you.

**Comment by Phr33d0m** [comment]
Let this stay open.

We can actually have an array of all the strings we use and different languages can be easily added/translated.

Something like

``` javascript
var lang = {
    'en': {
        'option.settings': 'Settings',
        'option.start': 'Start',
        ....
        'button.save': 'Save and apply',
    },
    'fr': {
        ...
    }
};
```

And in the rest of the code just do `lang[settings["language"]]["button.save"]` or whatever.

**Comment by noonereally** [comment]
yes, this is not hard to do, just a lot of work to copy paste and translate, but for now need only the titles and tool-tips and a bit headers.
And if possible to put it at the bottom of the script, somewhat less related, but  I've removed the 'inline' icons and recommend we move most of the change log to a separate file. Things start to take room and it becomes hard to find.

**Comment by GeneralSheppard** [comment]
Okay I would like to help.
Do you want that I gather all titles / tool-tips lines ?

**Comment by noonereally** [comment]
If you want to translate the tooltips and titles for now, 
try: https://github.com/noonereally/NW-Profession-Bot/blob/noonereally-temp1/main.js
I've compacted the settings into one per line anyway, maybe it will be easier so I uploaded it temporarily.
Lines 2064-2095

**Comment by GeneralSheppard** [comment]
Okay I'm on it :)
So I just modify titles and tooltips; right ?

**Comment by WloBeb** [comment]
Human readable profession names could be translated too ....
And also profile names. ;(

**Comment by GeneralSheppard** [comment]
I will check all titles and tooltips.
Then if a major version is available how it will be ? 
Do I have to rewrite everything ?

**Comment by WloBeb** [comment]
With git (github) there is no major/minor version.
Code is in a continuous developing. 
Developer could mark one of commits as version, but this is still only one of many commits.
As I understood <a href=https://github.com/Phr33d0m/NW-Profession-Bot/issues/91#issuecomment-101789453>this</a> comment you don't want to rewrite anything. 
It's only necessary to create one global object with translations and function to translate. The only problem is to call this function wherever it's necessary ;(

**Comment by WloBeb** [comment]
Unfortunately, there is one annoying problem with translation. Script uses taskListName property of definedTask eg. 'human readable' profession name to store settings. So we cann't simple translate this property if we do not want to define all the characters settings after each change of language.
We will need probably to add additional property to every defined task.
Besides, I have one question (probably to @Phr33d0m): is it acceptable to change the language involved manually reloading the page?

**Comment by GeneralSheppard** [comment]
Honestly it will be okay if the script stay friendly to read in english. 
I already spoke with my guildmates and all are okay.

I'm still ready to translate into French once scritp get language support.

**Comment by WloBeb** [comment]
With exception of two above problems translation support is easy to do. It requires only time to find all possible to translate texts and replace them with a function call.
To be honest, I already wrote this function, added settings for language and tested it with <s>couple of</s> one option string<s>s</s> translated.

**Comment by GeneralSheppard** [comment]
Let me know how I can help you doing this; I can replace a functin call maybe; i'm not that bad to follow orders.

**Comment by WloBeb** [comment]
If You are interested, look at <a href=https://github.com/Phr33d0m/NW-Profession-Bot/pull/95/files>this commit</a>. For now only first tab is allowed to translate. In lines 4973-4997 there is translation to my native language. You can translate to your language the same way. 
But you'd better wait and see if @Phr33d0m accept this commit :D.

**Comment by Phr33d0m** [comment]
Language support has already been added. If you want to contribute a translation see the available languages at the end of the file as an example.
