### ISSUE TITLE
Raspberry Pi support with Chronium ?

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#93]
Hello.

Can we have Rapberry Pi support with Chronium ?
It would be possible to make it run 24/24 7/7 well I think I do not have one yet but I would consider using it.

Thank.

**Comment by Phr33d0m** [comment]
I already run it on a Raspberry Pi 2. Why wouldn't it be possible?

**Comment by WloBeb** [comment]
@Phr33d0m It's a shame that you close this issue so quickly.
I wondered some time over the Raspberry PI, but discouraged me 1GB RAM.
Can you say something more about it?
Did you use Raspbian?
What browser are you using?
Do you have only one profile or more?
Did you start the real X server, or any virtual desktop?
And how much memory Rasbberry uses at your setup?
