### ISSUE TITLE
#Vendor options  auto-sell all red items (even unidentified)

### ISSUE THREAD

**Issue by GeneralSheppard** [Phr33d0m/NW-Profession-Bot#94]
Hello.

Would be interesting to get an option that allow to auto-sell all red items in inventory.

Best regards'

**Comment by Phr33d0m** [comment]
If by 'red items' you mean all the gear not for your class, I'm not sure if we can detect that or if it's worthy at all.

**Comment by GeneralSheppard** [comment]
Yes red items = all gear not for my class.
It's worthy because in low level we have plenty of it.

Ideas are launched :)

Have a nice day.

**Comment by GeneralSheppard** [comment]
I had a look into the source code and I am wondering (I'm nood I'm sorry)
If something like this 
                       _vendorItems[_vendorItems.lenght] = {
				pattern: /_Red_T[1-5]_Unid$/,
				limit: 0
			}; // Unidentified Red Gear

Would work and it is not working when I edited your script using Tampermonkey.

**Comment by noonereally** [comment]
Will need one item for example to be sure, but I think the items are not marked with "red" but with their class, so will have to save the current char class, and sell all Tier 1-5 unidentified items not of that class.

(I have not checked, so it's an assumption.)

**Comment by GeneralSheppard** [comment]
I was thinking the same Sir if you need help to gather item names or something let me know :)

**Comment by WloBeb** [comment]
As I see slot with item for different class has property 'hasclass' set to 0.
You probably can sell all items in slots when:
1. hasclass == 0
2. rariry == "Bronze"  or "Silver"
3. sellable == 1

**Comment by GeneralSheppard** [comment]
According to another post here is example about how "red items" for any other class look like:
https://github.com/Phr33d0m/NW-Profession-Bot/issues/90#issuecomment-102206975

Secondary_Scourge_V2_White_L33_Wpow_T3: x1
Feet_Controller_V2_Green_T3_Unid: x1 - unidentified

I would be interesting to have separate "auto vendor" options for BLUE items; maybe not for low level but can't be interesting to keep for AH selling?

**Comment by Phr33d0m** [comment]
Closing as per #247
